import { chromium } from 'playwright';
const BASE = process.env.PREVIEW_URL;
const OUT = process.env.SHOTS;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
p.on('console', m => { if (m.type() === 'error') console.log('CONSOLE-ERR:', m.text().slice(0, 160)); });
await p.goto(BASE, { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(3000);
console.log('URL:', p.url());
console.log('TITLE:', await p.title());
await p.screenshot({ path: `${OUT}/e0-landing.png` });
const inputs = await p.locator('input').count();
console.log('inputs:', inputs);
const btns = await p.locator('button').allInnerTexts();
console.log('buttons:', JSON.stringify(btns.slice(0, 30)));
console.log('bodytext:', (await p.innerText('body')).replace(/\s+/g, ' ').slice(0, 400));
await b.close();
