import { useState, useEffect, useCallback, useRef, type ClipboardEvent } from 'react';
import { ArrowLeft, Save, Send, Plus, Trash2, Sparkles, FileText, Check, AlertCircle, Upload } from 'lucide-react';
import { MapSpinner } from '@/components/ui/VideoLoader';
import { GlassCard } from '@/components/design/GlassCard';
import { Button } from '@/components/design/Button';
import { toast } from '@/lib/toast';
import { systemDialog } from '@/lib/systemDialog';
import { useReportAgentStore } from '@/stores/reportAgentStore';
import { useAutosave } from '@/hooks/useAutosave';
import { compressImageToLimit, hasMarkdownImage, MAX_RICH_TEXT_IMAGE_BYTES } from '@/lib/imageCompress';
import {
  createWeeklyReport,
  updateWeeklyReport,
  submitWeeklyReport,
  getWeeklyReport,
  generateReport,
  deleteWeeklyReport,
  uploadReportRichTextImage,
  listMyAiSources,
  listPersonalSources,
  getMyDefaultTemplate,
  getTeamDefaultTemplate,
} from '@/services';
import type { WeeklyReport, ReportAiSource, PersonalSource } from '@/services/contracts/reportAgent';
import { WeeklyReportStatus, ReportInputType, WeeklyReportCreationMode } from '@/services/contracts/reportAgent';
import { RichTextMarkdownContent } from './RichTextMarkdownContent';
import { MarkdownImportModal } from './MarkdownImportModal';
import { useDataTheme, type DataTheme } from '../hooks/useDataTheme';

// 节号配色:暗色模式保留多彩,浅色下压成克制的 editorial 单色 + 左侧色条 hint
const SECTION_RGB = [
  '59, 130, 246',  // blue
  '34, 197, 94',   // green
  '168, 85, 247',  // purple
  '249, 115, 22',  // orange
  '236, 72, 153',  // pink
  '20, 184, 166',  // teal
];

interface SectionTheme {
  color: string;        // 章节标识色 (数字徽章/左边线)
  bg: string;           // header 背景 (浅色下透明,暗色下淡色)
  border: string;       // section 外边框
  badgeBg: string;      // 数字徽章背景
  badgeColor: string;   // 数字徽章文字
  headerBorder: string; // header 底部分隔线
}

function buildSectionThemes(theme: DataTheme): SectionTheme[] {
  const isLight = theme === 'light';
  if (isLight) {
    // 浅色:去掉大色条,改 editorial 克制风
    // - header 背景 transparent,靠左侧 3px 色条 + 底部 hairline 分层
    // - 数字徽章改为深色单色 (slate-900) + 白字,不用饱和彩色
    return SECTION_RGB.map((rgb) => ({
      color:        `rgba(${rgb}, 1)`,                    // 左侧 3px accent
      bg:           'transparent',                         // 不再整行填色
      border:       'var(--hairline)',                     // section 外框细线
      badgeBg:      '#0F172A',                             // slate-900 统一数字徽章
      badgeColor:   '#FFFFFF',
      headerBorder: 'var(--hairline)',                     // header 下沿细线
    }));
  }
  // 暗色:保留原发光感
  return SECTION_RGB.map((rgb) => ({
    color:        `rgba(${rgb}, 0.9)`,
    bg:           `rgba(${rgb}, 0.06)`,
    border:       `rgba(${rgb}, 0.15)`,
    badgeBg:      `rgba(${rgb}, 0.9)`,
    badgeColor:   '#FFFFFF',
    headerBorder: `rgba(${rgb}, 0.15)`,
  }));
}

interface Props {
  reportId: string | null;
  weekYear: number;
  weekNumber: number;
  onClose: () => void;
}

type ReportCreationMode = (typeof WeeklyReportCreationMode)[keyof typeof WeeklyReportCreationMode];

const SOURCE_KEY_ALIASES: Record<string, string> = {
  daily_log: 'daily-log',
  system_activity: 'map-platform',
  map_activity: 'map-platform',
  git: 'map-platform',
  tapd: 'map-platform',
};

const DEFAULT_SOURCE_LABELS: Record<string, string> = {
  'daily-log': '日常记录',
  'map-platform': 'MAP平台工作记录',
  github: 'GitHub',
  yuque: '语雀',
  ai: 'AI归纳',
};

function normalizeSourceKey(source?: string): string {
  if (!source) return '';
  const normalized = source.trim().toLowerCase();
  return SOURCE_KEY_ALIASES[normalized] ?? normalized;
}

function countReportItems(report: Pick<WeeklyReport, 'sections'>): number {
  return report.sections.reduce((sum, section) => sum + section.items.length, 0);
}

function resolveGenerationModelLabel(report: Pick<WeeklyReport, 'autoGeneratedBy' | 'autoGeneratedModelId'>): string {
  if (report.autoGeneratedBy === 'rule-fallback') return '规则兜底';
  return report.autoGeneratedModelId || '未记录模型';
}

/** 编辑器内每个 item 的草稿状态（比 WeeklyReportItem 略宽,包含 IssueList 扩展字段） */
interface ItemDraft {
  content: string;
  source: string;
  sourceRef?: string;
  issueCategoryKey?: string;
  issueStatusKey?: string;
  imageUrls?: string[];
}

/** 把后端 WeeklyReportItem 映射为本地草稿（保留所有字段） */
function toItemDraft(i: { content: string; source: string; sourceRef?: string; issueCategoryKey?: string; issueStatusKey?: string; imageUrls?: string[] }): ItemDraft {
  return {
    content: i.content,
    source: i.source,
    sourceRef: i.sourceRef,
    issueCategoryKey: i.issueCategoryKey,
    issueStatusKey: i.issueStatusKey,
    imageUrls: i.imageUrls ? [...i.imageUrls] : undefined,
  };
}

/** IssueList 单项卡片：富文本 textarea + 分类/状态下拉 + 预览。
    图片通过粘贴进 textarea 走 markdown 嵌入 content(复用现有 RichText 粘贴上传机制)。 */
function IssueItemCard({
  item, categories, statuses, canEdit, isLight, themeBorder,
  onChange, onPasteImage, pasting,
}: {
  item: ItemDraft;
  categories: import('@/services/contracts/reportAgent').IssueOption[];
  statuses: import('@/services/contracts/reportAgent').IssueOption[];
  canEdit: boolean;
  isLight: boolean;
  themeBorder: string;
  onChange: (patch: Partial<ItemDraft>) => void;
  onPasteImage: (e: ClipboardEvent<HTMLTextAreaElement>) => void;
  pasting: boolean;
}) {
  return (
    <div
      className="flex-1 rounded-xl p-3 flex flex-col gap-2.5"
      style={{
        background: isLight ? 'var(--bg-nested)' : 'var(--bg-secondary)',
        border: `1px solid ${themeBorder}`,
      }}
    >
      {/* 分类 + 状态 */}
      <div className="flex items-center gap-2 flex-wrap">
        <label className="text-[11px]" style={{ color: 'var(--text-muted)' }}>分类</label>
        <select
          className="px-2 py-1 rounded-md text-[12px]"
          style={{ background: 'var(--bg-secondary)', color: 'var(--text-primary)', border: '1px solid var(--border-primary)' }}
          value={item.issueCategoryKey || ''}
          onChange={(e) => onChange({ issueCategoryKey: e.target.value || undefined })}
          disabled={!canEdit || categories.length === 0}
        >
          <option value="">— 未选择 —</option>
          {categories.map((c) => (
            <option key={c.key} value={c.key}>{c.label}</option>
          ))}
        </select>
        <label className="text-[11px] ml-2" style={{ color: 'var(--text-muted)' }}>状态</label>
        <select
          className="px-2 py-1 rounded-md text-[12px]"
          style={{ background: 'var(--bg-secondary)', color: 'var(--text-primary)', border: '1px solid var(--border-primary)' }}
          value={item.issueStatusKey || ''}
          onChange={(e) => onChange({ issueStatusKey: e.target.value || undefined })}
          disabled={!canEdit || statuses.length === 0}
        >
          <option value="">— 未选择 —</option>
          {statuses.map((s) => (
            <option key={s.key} value={s.key}>{s.label}</option>
          ))}
        </select>
      </div>

      {/* 富文本 textarea(支持粘贴图片,和 RichText 一致) */}
      <textarea
        className="w-full px-3 py-2 rounded-lg text-[13px] resize-none transition-all duration-200"
        style={{
          background: isLight ? 'var(--bg-base)' : 'var(--bg-secondary)',
          color: 'var(--text-primary)',
          border: '1px solid var(--border-primary)',
          minHeight: 90,
          outline: 'none',
        }}
        value={item.content}
        onChange={(e) => onChange({ content: e.target.value })}
        onPaste={onPasteImage}
        placeholder={pasting ? '图片上传中...' : '描述问题细节（支持 Markdown + 粘贴图片）...'}
        disabled={!canEdit}
      />

      {/* 内嵌图片预览（来自 markdown ![...](url)） */}
      {hasMarkdownImage(item.content) && (
        <RichTextMarkdownContent
          content={item.content}
          showRealtimeLabel
          imageMaxHeight={200}
        />
      )}
    </div>
  );
}

export function ReportEditor({ reportId, weekYear, weekNumber, onClose }: Props) {
  const { teams, templates, updateReportInList, addReportToList, removeReportFromList } = useReportAgentStore();
  const [report, setReport] = useState<WeeklyReport | null>(null);
  const [sections, setSections] = useState<{ items: ItemDraft[] }[]>([]);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [createModeLoading, setCreateModeLoading] = useState<ReportCreationMode | null>(null);
  const [pastingImageKey, setPastingImageKey] = useState<string | null>(null);
  const [selectedTeamId, setSelectedTeamId] = useState(teams[0]?.id || '');
  const [selectedTemplateId, setSelectedTemplateId] = useState(templates[0]?.id || '');
  const [myDefaultTemplateId, setMyDefaultTemplateId] = useState<string | null>(null);
  const [teamDefaultTemplateId, setTeamDefaultTemplateId] = useState<string | null>(null);
  const [isNew, setIsNew] = useState(!reportId);
  const [showMarkdownImport, setShowMarkdownImport] = useState(false);
  const [loadFailed, setLoadFailed] = useState<string | null>(null);

  // 浅色 / 暗色模式感知,供下文所有 inline style 使用
  const dataTheme = useDataTheme();
  const isLight = dataTheme === 'light';
  const sectionThemes = buildSectionThemes(dataTheme);

  // 当为新建时，预填用户个人默认模板偏好（后端 my-default 接口）
  useEffect(() => {
    if (!isNew) return;
    let cancelled = false;
    (async () => {
      const res = await getMyDefaultTemplate();
      if (cancelled || !res.success || !res.data?.template?.id) return;
      setMyDefaultTemplateId(res.data.template.id);
      setSelectedTemplateId((prev) => prev || res.data!.template!.id);
    })();
    return () => { cancelled = true; };
  }, [isNew]);

  // 团队改变时，拉取该团队的默认模板，若用户尚未自主选过则联动设置
  useEffect(() => {
    if (!isNew || !selectedTeamId) {
      setTeamDefaultTemplateId(null);
      return;
    }
    let cancelled = false;
    (async () => {
      const res = await getTeamDefaultTemplate({ teamId: selectedTeamId });
      if (cancelled || !res.success) return;
      const tplId = res.data?.template?.id ?? null;
      setTeamDefaultTemplateId(tplId);
      if (tplId) {
        // 团队默认优先级高于个人偏好（因为用户明确选了这个团队的周报）
        setSelectedTemplateId(tplId);
      }
    })();
    return () => { cancelled = true; };
  }, [isNew, selectedTeamId]);
  const [sourceLabelMap, setSourceLabelMap] = useState<Record<string, string>>(DEFAULT_SOURCE_LABELS);

  const isEditableStatus = !report
    || report.status === WeeklyReportStatus.Draft
    || report.status === WeeklyReportStatus.Submitted
    || report.status === WeeklyReportStatus.Returned
    || report.status === WeeklyReportStatus.Overdue;

  const reportIdForSave = report?.id ?? null;
  const updateReportInListRef = useRef(updateReportInList);
  useEffect(() => { updateReportInListRef.current = updateReportInList; }, [updateReportInList]);

  const autosaveOnSave = useCallback(async (secs: typeof sections) => {
    if (!reportIdForSave) return { success: false, message: '周报尚未创建' };
    const res = await updateWeeklyReport({ id: reportIdForSave, sections: secs });
    if (res.success && res.data) {
      setReport(res.data.report);
      updateReportInListRef.current(res.data.report);
      return { success: true };
    }
    return { success: false, message: res.error?.message };
  }, [reportIdForSave]);

  const autosave = useAutosave({
    value: sections,
    enabled: !!reportIdForSave && isEditableStatus && !generating && !deleting,
    onSave: autosaveOnSave,
    delayMs: 1500,
    warnBeforeUnload: true,
  });

  useEffect(() => {
    let disposed = false;
    (async () => {
      try {
        const [aiRes, personalRes] = await Promise.all([listMyAiSources(), listPersonalSources()]);
        if (disposed) return;

        const nextMap: Record<string, string> = { ...DEFAULT_SOURCE_LABELS };
        if (aiRes.success && aiRes.data) {
          for (const item of aiRes.data.items as ReportAiSource[]) {
            const key = normalizeSourceKey(item.key);
            if (key) nextMap[key] = item.name;
          }
        }
        if (personalRes.success && personalRes.data) {
          for (const item of personalRes.data.items as PersonalSource[]) {
            const key = normalizeSourceKey(item.sourceType);
            if (key && !nextMap[key]) nextMap[key] = item.displayName;
          }
        }
        setSourceLabelMap(nextMap);
      } catch {
        // 保留默认映射，不中断编辑流程
      }
    })();
    return () => { disposed = true; };
  }, []);

  const resolveSourceLabel = useCallback((source: string) => {
    const normalized = normalizeSourceKey(source);
    return sourceLabelMap[normalized] || sourceLabelMap[source] || source;
  }, [sourceLabelMap]);

  const renderSourceBadge = useCallback((source?: string) => {
    const normalized = normalizeSourceKey(source);
    if (!normalized || normalized === 'manual') return null;
    const isAi = normalized === 'ai';
    // 浅色模式下使用更深的文字色 + 更显眼的描边,确保浅底上仍可读
    const aiColor = isLight ? 'rgba(126, 34, 206, 0.95)' : 'rgba(196, 138, 255, 0.96)';
    const sourceColor = isLight ? 'rgba(2, 132, 199, 0.95)' : 'rgba(125, 211, 252, 0.96)';
    const aiBg = isLight ? 'rgba(168, 85, 247, 0.10)' : 'rgba(168, 85, 247, 0.16)';
    const sourceBg = isLight ? 'rgba(56, 189, 248, 0.10)' : 'rgba(56, 189, 248, 0.16)';
    const aiBorder = isLight ? 'rgba(168, 85, 247, 0.30)' : 'rgba(168, 85, 247, 0.35)';
    const sourceBorder = isLight ? 'rgba(56, 189, 248, 0.32)' : 'rgba(56, 189, 248, 0.35)';
    return (
      <span
        className="text-[10px] px-2 py-1 rounded-full self-center flex-shrink-0 font-medium border"
        style={{
          color: isAi ? aiColor : sourceColor,
          background: isAi ? aiBg : sourceBg,
          borderColor: isAi ? aiBorder : sourceBorder,
        }}
        title={normalized}
      >
        {resolveSourceLabel(normalized)}
      </span>
    );
  }, [resolveSourceLabel]);

  useEffect(() => {
    if (!reportId) return;
    setLoadFailed(null);
    (async () => {
      const res = await getWeeklyReport({ id: reportId });
      if (res.success && res.data) {
        setReport(res.data.report);
        setSections(
          res.data.report.sections.map((s) => ({
            items: s.items.length > 0
              ? s.items.map(toItemDraft)
              : [{ content: '', source: 'manual' }],
          }))
        );
        setIsNew(false);
      } else {
        // 不再静默白屏:显式 toast + 渲染 fallback,避免按钮看似消失
        const message = res.error?.message || '周报加载失败，请刷新重试';
        toast.error(message);
        setLoadFailed(message);
      }
    })();
  }, [reportId]);

  const handleCreate = useCallback(async (creationMode: ReportCreationMode) => {
    if (!selectedTeamId || !selectedTemplateId) {
      toast.error('请选择团队和模板');
      return;
    }
    if (creationMode === WeeklyReportCreationMode.AiDraft) {
      const ok = await systemDialog.confirm({
        title: '确认使用 AI 生成草稿？',
        message: '将按当前周数据和模板自动生成周报草稿。\n生成后你仍可手动编辑和调整内容。',
        confirmText: '开始生成',
        cancelText: '返回',
      });
      if (!ok) return;
    }
    setCreateModeLoading(creationMode);
    const res = await createWeeklyReport({
      teamId: selectedTeamId,
      templateId: selectedTemplateId,
      weekYear,
      weekNumber,
      creationMode,
    });
    setCreateModeLoading(null);
    if (res.success && res.data) {
      setReport(res.data.report);
      setSections(
        res.data.report.sections.map((s) => ({
          items: s.items.length > 0
            ? s.items.map(toItemDraft)
            : [{ content: '', source: 'manual' }],
        }))
      );
      setIsNew(false);
      addReportToList(res.data.report);
      if (creationMode === WeeklyReportCreationMode.AiDraft) {
        const generatedItemCount = countReportItems(res.data.report);
        if (res.data.aiGenerationError) {
          toast.error(`草稿已创建，但 AI 生成失败：${res.data.aiGenerationError}`);
          return;
        }
        if (res.data.report.autoGeneratedAt && generatedItemCount > 0) {
          toast.success(`AI 周报草稿已生成（${resolveGenerationModelLabel(res.data.report)}）`);
        } else {
          toast.error('草稿已创建，但 AI 生成失败，请手动补充');
        }
      } else {
        toast.success('周报已创建');
      }
    } else {
      toast.error(res.error?.message || '创建失败');
    }
  }, [selectedTeamId, selectedTemplateId, weekYear, weekNumber, addReportToList]);

  const handleSave = useCallback(async () => {
    if (!report) return;
    setSaving(true);
    const result = await autosave.flush();
    setSaving(false);
    if (result.success) {
      toast.success('已保存');
    } else {
      toast.error(result.message || '保存失败');
    }
  }, [report, autosave]);

  const handleSubmit = useCallback(async () => {
    if (!report) return;
    setSaving(true);
    const flushResult = await autosave.flush();
    if (!flushResult.success) {
      setSaving(false);
      toast.error(flushResult.message || '保存失败');
      return;
    }
    const res = await submitWeeklyReport({ id: report.id });
    setSaving(false);
    if (res.success && res.data) {
      updateReportInList(res.data.report);
      toast.success('周报已提交');
      onClose();
    } else {
      toast.error(res.error?.message || '提交失败');
    }
  }, [report, autosave, updateReportInList, onClose]);

  const handleGenerate = useCallback(async () => {
    if (!report) return;
    const ok = await systemDialog.confirm({
      title: '确认重新生成草稿？',
      message: '将基于当前周采集数据重新生成周报草稿。\n当前编辑内容会被覆盖，建议先保存后再执行。',
      tone: 'danger',
      confirmText: '重新生成',
      cancelText: '取消',
    });
    if (!ok) return;
    setGenerating(true);
    try {
      const res = await generateReport({ id: report.id });
      if (res.success && res.data) {
        const updated = res.data;
        const generatedItemCount = countReportItems(updated);
        if (generatedItemCount <= 0) {
          toast.error('AI 未生成有效内容，本次未覆盖当前草稿');
          return;
        }
        setReport(updated);
        setSections(
          updated.sections.map((s) => ({
            items: s.items.length > 0
              ? s.items.map(toItemDraft)
              : [{ content: '', source: 'manual' }],
          }))
        );
        updateReportInList(updated);
        autosave.markSaved();
        toast.success(`AI 已重新生成周报草稿（${resolveGenerationModelLabel(updated)}）`);
      } else {
        toast.error(res.error?.message || 'AI 生成失败');
      }
    } catch {
      toast.error('AI 生成失败，请稍后重试');
    } finally {
      setGenerating(false);
    }
  }, [report, updateReportInList, autosave]);

  const handleDelete = useCallback(async () => {
    if (!report) return;
    const ok = await systemDialog.confirm({
      title: '确认删除周报？',
      message: '删除后不可恢复，请确认是否删除这份周报。',
      tone: 'danger',
      confirmText: '确认删除',
      cancelText: '取消',
    });
    if (!ok) return;

    setDeleting(true);
    const res = await deleteWeeklyReport({ id: report.id });
    setDeleting(false);
    if (res.success) {
      removeReportFromList(report.id);
      toast.success('周报已删除');
      onClose();
    } else {
      toast.error(res.error?.message || '删除失败');
    }
  }, [report, removeReportFromList, onClose]);

  const updateItem = (sectionIdx: number, itemIdx: number, content: string) => {
    setSections((prev) => {
      const next = [...prev];
      next[sectionIdx] = {
        ...next[sectionIdx],
        items: next[sectionIdx].items.map((item, i) =>
          i === itemIdx ? { ...item, content } : item
        ),
      };
      return next;
    });
  };

  /** IssueList 专用:更新 item 的任意字段（分类/状态/图片列表） */
  const updateItemFields = (sectionIdx: number, itemIdx: number, patch: Partial<ItemDraft>) => {
    setSections((prev) => {
      const next = [...prev];
      next[sectionIdx] = {
        ...next[sectionIdx],
        items: next[sectionIdx].items.map((item, i) =>
          i === itemIdx ? { ...item, ...patch } : item
        ),
      };
      return next;
    });
  };

  const addItem = (sectionIdx: number) => {
    setSections((prev) => {
      const next = [...prev];
      next[sectionIdx] = {
        ...next[sectionIdx],
        items: [...next[sectionIdx].items, { content: '', source: 'manual' }],
      };
      return next;
    });
  };

  const removeItem = (sectionIdx: number, itemIdx: number) => {
    setSections((prev) => {
      const next = [...prev];
      next[sectionIdx] = {
        ...next[sectionIdx],
        items: next[sectionIdx].items.filter((_, i) => i !== itemIdx),
      };
      return next;
    });
  };

  const bulletInputRefsRef = useRef<Record<string, HTMLInputElement | null>>({});

  const focusBulletAt = useCallback((sectionIdx: number, itemIdx: number, caret: 'start' | 'end' = 'end') => {
    requestAnimationFrame(() => {
      const el = bulletInputRefsRef.current[`${sectionIdx}:${itemIdx}`];
      if (!el) return;
      el.focus();
      const pos = caret === 'end' ? el.value.length : 0;
      try { el.setSelectionRange(pos, pos); } catch { /* ignore */ }
    });
  }, []);

  const handleBulletKeyDown = useCallback((
    sectionIdx: number,
    itemIdx: number,
    e: React.KeyboardEvent<HTMLInputElement>,
  ) => {
    const target = e.currentTarget;
    if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
      e.preventDefault();
      if (target.value.trim() === '') return;
      addItem(sectionIdx);
      focusBulletAt(sectionIdx, itemIdx + 1, 'start');
      return;
    }
    if (e.key === 'Backspace' && target.value === '' && target.selectionStart === 0 && target.selectionEnd === 0) {
      const currentItems = sections[sectionIdx]?.items || [];
      if (currentItems.length <= 1) return;
      e.preventDefault();
      removeItem(sectionIdx, itemIdx);
      const prevIdx = Math.max(0, itemIdx - 1);
      focusBulletAt(sectionIdx, prevIdx, 'end');
    }
  }, [sections, focusBulletAt]);

  const canEdit = isEditableStatus;
  const canSubmit = !!report
    && (report.status === WeeklyReportStatus.Draft
      || report.status === WeeklyReportStatus.Returned
      || report.status === WeeklyReportStatus.Overdue);
  const canGenerate = !!report
    && (report.status === WeeklyReportStatus.Draft
      || report.status === WeeklyReportStatus.Returned
      || report.status === WeeklyReportStatus.Overdue);
  const canDelete = !!report
    && (report.status === WeeklyReportStatus.Draft
      || report.status === WeeklyReportStatus.Submitted
      || report.status === WeeklyReportStatus.Returned
      || report.status === WeeklyReportStatus.Overdue);

  // 旧库 / 新枚举值导致按钮全部隐藏时,留下日志方便定位"按钮消失"问题
  useEffect(() => {
    if (report && !canEdit && !canSubmit && !canGenerate && !canDelete && import.meta.env.DEV) {
      console.warn(
        '[ReportEditor] 周报状态非可操作值,所有按钮已隐藏 — 可能是新枚举未在前端登记',
        { reportId: report.id, status: report.status }
      );
    }
  }, [report, canEdit, canSubmit, canGenerate, canDelete]);

  const handleRichTextPaste = async (
    e: ClipboardEvent<HTMLTextAreaElement>,
    sectionIdx: number,
    itemIdx: number
  ) => {
    if (!report || !canEdit) return;
    const textarea = e.currentTarget;
    const imageItem = Array.from(e.clipboardData?.items ?? []).find((it) => it.type.startsWith('image/'));
    if (!imageItem) return;

    const file = imageItem.getAsFile();
    if (!file) return;

    e.preventDefault();
    const uploadKey = `${sectionIdx}-${itemIdx}`;
    setPastingImageKey(uploadKey);

    try {
      const { file: uploadFile, compressed } = await compressImageToLimit(file, MAX_RICH_TEXT_IMAGE_BYTES);
      const res = await uploadReportRichTextImage({ id: report.id, file: uploadFile });
      if (!res.success || !res.data?.url) {
        toast.error(res.error?.message || '图片上传失败');
        return;
      }

      const start = textarea.selectionStart ?? textarea.value.length;
      const end = textarea.selectionEnd ?? start;
      const current = textarea.value;
      const markdown = `\n![粘贴图片](${res.data.url})\n`;
      const next = `${current.slice(0, start)}${markdown}${current.slice(end)}`;
      updateItem(sectionIdx, itemIdx, next);

      const cursor = start + markdown.length;
      requestAnimationFrame(() => {
        textarea.focus();
        textarea.setSelectionRange(cursor, cursor);
      });

      toast.success(compressed ? '图片已自动压缩并插入' : '图片已插入');
    } catch (error) {
      toast.error(error instanceof Error ? error.message : '图片处理失败');
    } finally {
      setPastingImageKey((prev) => (prev === uploadKey ? null : prev));
    }
  };

  // sectionThemes / isLight 已在组件顶部声明

  // Create flow
  if (isNew && !report) {
    return (
      <div className="flex flex-col gap-6">
        {/* Back + title */}
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={onClose}>
            <ArrowLeft size={16} />
          </Button>
          <div>
            <div
              className="text-[20px] font-semibold"
              style={{
                color: 'var(--text-primary)',
                fontFamily: isLight ? 'var(--font-serif)' : undefined,
                letterSpacing: isLight ? '-0.01em' : undefined,
                lineHeight: 1.2,
              }}
            >
              创建周报
            </div>
            <div className="text-[12px] mt-1" style={{ color: 'var(--text-muted)' }}>
              {weekYear} 年第 {weekNumber} 周
            </div>
          </div>
        </div>

        {/* Create card */}
        <div className="max-w-lg">
          <GlassCard className="p-6">
            <div className="flex items-center gap-3 mb-5">
              <div
                className="w-10 h-10 rounded-xl flex items-center justify-center"
                style={{ background: isLight ? 'var(--accent-claude-soft)' : 'rgba(59, 130, 246, 0.08)' }}
              >
                <FileText size={18} style={{ color: isLight ? 'var(--accent-claude)' : 'rgba(59, 130, 246, 0.9)' }} />
              </div>
              <div>
                <div className="text-[14px] font-medium" style={{ color: 'var(--text-primary)' }}>选择团队和模板</div>
                <div className="text-[12px]" style={{ color: 'var(--text-muted)' }}>创建后可随时编辑和保存</div>
              </div>
            </div>
            <div className="flex flex-col gap-4">
              <div>
                <label className="text-[12px] font-medium mb-2 block" style={{ color: 'var(--text-secondary)' }}>所属团队</label>
                <select
                  className="w-full px-3.5 py-2.5 rounded-xl text-[13px]"
                  style={{ background: 'var(--bg-secondary)', color: 'var(--text-primary)', border: '1px solid var(--border-primary)' }}
                  value={selectedTeamId}
                  onChange={(e) => setSelectedTeamId(e.target.value)}
                >
                  <option value="">请选择团队</option>
                  {teams.map((t) => (
                    <option key={t.id} value={t.id}>{t.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="text-[12px] font-medium mb-2 block" style={{ color: 'var(--text-secondary)' }}>周报模板</label>
                <select
                  className="w-full px-3.5 py-2.5 rounded-xl text-[13px]"
                  style={{ background: 'var(--bg-secondary)', color: 'var(--text-primary)', border: '1px solid var(--border-primary)' }}
                  value={selectedTemplateId}
                  onChange={(e) => setSelectedTemplateId(e.target.value)}
                >
                  <option value="">请选择模板</option>
                  {templates.map((t) => {
                    const suffix = teamDefaultTemplateId === t.id
                      ? ' (团队默认)'
                      : myDefaultTemplateId === t.id
                        ? ' (我的默认)'
                        : t.isDefault && t.isSystem
                          ? ' (系统默认)'
                          : '';
                    return (
                      <option key={t.id} value={t.id}>{t.name}{suffix}</option>
                    );
                  })}
                </select>
              </div>
              <div className="grid grid-cols-2 gap-2 mt-1">
                <Button
                  variant="secondary"
                  onClick={() => { void handleCreate(WeeklyReportCreationMode.Manual); }}
                  disabled={!!createModeLoading || !selectedTeamId || !selectedTemplateId}
                  className="whitespace-nowrap"
                >
                  {createModeLoading === WeeklyReportCreationMode.Manual ? '创建中...' : '手动填写'}
                </Button>
                <Button
                  variant="primary"
                  onClick={() => { void handleCreate(WeeklyReportCreationMode.AiDraft); }}
                  disabled={!!createModeLoading || !selectedTeamId || !selectedTemplateId}
                  className="whitespace-nowrap"
                >
                  {createModeLoading === WeeklyReportCreationMode.AiDraft ? (
                    <><MapSpinner size={13} /> 生成中...</>
                  ) : (
                    <><Sparkles size={13} /> AI生成周报草稿</>
                  )}
                </Button>
              </div>
              {/* 次级入口：从 Markdown 文件导入 —— 不分散主推的 AI 草稿 */}
              <button
                type="button"
                onClick={() => {
                  if (!selectedTeamId || !selectedTemplateId) {
                    toast.error('请先选择团队和模板');
                    return;
                  }
                  setShowMarkdownImport(true);
                }}
                disabled={!!createModeLoading || !selectedTeamId || !selectedTemplateId}
                className="text-[12px] mt-2 inline-flex items-center gap-1.5 self-center opacity-80 hover:opacity-100 disabled:opacity-40 disabled:cursor-not-allowed transition"
                style={{ color: 'var(--text-secondary)' }}
              >
                <Upload size={12} />
                或 从 Markdown 文件导入
              </button>
            </div>
          </GlassCard>
        </div>

        {/* Markdown 导入弹窗 */}
        {showMarkdownImport && selectedTeamId && selectedTemplateId && (() => {
          const team = teams.find((t) => t.id === selectedTeamId);
          const template = templates.find((t) => t.id === selectedTemplateId);
          if (!team || !template) return null;
          return (
            <MarkdownImportModal
              teamId={team.id}
              teamName={team.name}
              templateId={template.id}
              templateName={template.name}
              template={template}
              weekYear={weekYear}
              weekNumber={weekNumber}
              onImported={(imported) => {
                setReport(imported);
                setSections(
                  imported.sections.map((s) => ({
                    items: s.items.length > 0
                      ? s.items.map(toItemDraft)
                      : [{ content: '', source: 'manual' }],
                  }))
                );
                setIsNew(false);
                addReportToList(imported);
              }}
              onClose={() => setShowMarkdownImport(false)}
            />
          );
        })()}
      </div>
    );
  }

  if (!report) {
    if (loadFailed) {
      return (
        <div className="flex flex-col gap-4 h-full min-h-0">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="sm" onClick={onClose}>
              <ArrowLeft size={16} />
            </Button>
          </div>
          <GlassCard className="p-8 flex flex-col items-center text-center gap-3 max-w-md self-center">
            <AlertCircle size={28} style={{ color: 'rgba(239, 68, 68, 0.85)' }} />
            <div className="text-[15px] font-medium" style={{ color: 'var(--text-primary)' }}>
              周报加载失败
            </div>
            <div className="text-[12px]" style={{ color: 'var(--text-muted)' }}>
              {loadFailed}
            </div>
            <div className="text-[11px]" style={{ color: 'var(--text-muted)' }}>
              可能是网络波动，或你已无权访问该周报。
            </div>
            <div className="flex items-center gap-2 mt-2">
              <Button variant="secondary" size="sm" onClick={onClose}>
                返回列表
              </Button>
            </div>
          </GlassCard>
        </div>
      );
    }
    return null;
  }
  const generationModelLabel = report.autoGeneratedBy === 'rule-fallback'
    ? '规则兜底'
    : (report.autoGeneratedModelId || '未记录模型');

  // Calculate progress
  const totalItems = sections.reduce((sum, s) => sum + s.items.length, 0);
  const filledItems = sections.reduce(
    (sum, s) => sum + s.items.filter((i) => i.content.trim()).length, 0
  );
  const progress = totalItems > 0 ? Math.round((filledItems / totalItems) * 100) : 0;

  return (
    <div className="flex flex-col gap-5 h-full min-h-0">
      {/* Header toolbar — now in a card */}
      <GlassCard variant="subtle" className="px-5 py-3">
        {/* flex-wrap + gap-3:窄屏 / zoom 放大 / 多按钮场景下,「提交」按钮不再被挤出可视区 */}
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3 min-w-0">
            <Button variant="ghost" size="sm" onClick={onClose}>
              <ArrowLeft size={16} />
            </Button>
            <div>
              <div className="flex items-center gap-2">
                <span
                  className="text-[17px] font-semibold"
                  style={{
                    color: 'var(--text-primary)',
                    fontFamily: isLight ? 'var(--font-serif)' : undefined,
                    letterSpacing: isLight ? '-0.01em' : undefined,
                  }}
                >
                  {report.teamName}
                </span>
                <span
                  className="text-[11px] px-2 py-0.5 rounded-full"
                  style={{ color: 'var(--text-muted)', background: 'var(--bg-tertiary)' }}
                >
                  {report.weekYear} 年第 {report.weekNumber} 周
                </span>
              </div>
              {/* Mini progress bar — 浅色下走 Claude 橙 */}
              {canEdit && totalItems > 0 && (
                <div className="flex items-center gap-2 mt-1.5">
                  <div
                    className="w-24 h-1.5 rounded-full overflow-hidden"
                    style={{ background: isLight ? 'var(--border-faint)' : 'var(--bg-tertiary)' }}
                  >
                    <div
                      className="h-full rounded-full transition-all duration-500"
                      style={{
                        width: `${progress}%`,
                        // 进行中走克制 slate(浅) / muted blue(暗) — 完成才是事件,在 100% 时上 sage 绿
                        background: progress === 100
                          ? (isLight ? 'var(--status-done)' : 'rgba(34, 197, 94, 0.7)')
                          : (isLight ? 'rgba(15, 23, 42, 0.32)' : 'rgba(255, 255, 255, 0.20)'),
                      }}
                    />
                  </div>
                  <span className="text-[10px]" style={{ color: 'var(--text-muted)' }}>
                    {filledItems}/{totalItems} 已填写
                  </span>
                </div>
              )}
            </div>
          </div>
          {(canEdit || canSubmit || canGenerate || canDelete) && (
            <div className="flex items-center gap-2 flex-wrap shrink-0 ml-auto">
              {canEdit && (
                <AutosaveIndicator
                  status={autosave.status}
                  lastSavedAt={autosave.lastSavedAt}
                  lastError={autosave.lastError}
                  onRetry={() => { void autosave.flush(); }}
                />
              )}
              {canGenerate && (
                <Button variant="secondary" size="sm" onClick={handleGenerate} disabled={generating || saving || deleting}>
                  {generating ? (
                    <><MapSpinner size={13} /> 生成中...</>
                  ) : (
                    <><Sparkles size={13} /> AI重新生成草稿</>
                  )}
                </Button>
              )}
              {canEdit && (
                <Button variant="secondary" size="sm" onClick={handleSave} disabled={saving || generating || deleting}>
                  <Save size={13} /> 保存
                </Button>
              )}
              {canSubmit && (
                <Button variant="primary" size="sm" onClick={handleSubmit} disabled={saving || generating || deleting}>
                  <Send size={13} /> 提交
                </Button>
              )}
              {canDelete && (
                <Button variant="ghost" size="sm" onClick={handleDelete} disabled={saving || generating || deleting}>
                  <Trash2 size={13} /> {deleting ? '删除中...' : '删除'}
                </Button>
              )}
            </div>
          )}
        </div>
      </GlassCard>

      {/* AI banner — editorial note 风：去面板化,只保留左侧 2px 线 + 无底色文本 */}
      {report.autoGeneratedAt && (
        <div
          className="flex items-center gap-2.5 text-[12px] pl-4 pr-5 py-2.5"
          style={{
            color: isLight ? 'var(--text-secondary)' : 'rgba(168, 85, 247, 0.9)',
            background: isLight ? 'transparent' : 'rgba(168, 85, 247, 0.06)',
            borderLeft: `2px solid ${isLight ? 'rgba(126, 34, 206, 0.55)' : 'rgba(168, 85, 247, 0.5)'}`,
            borderRadius: isLight ? '2px' : '12px',
            border: isLight ? undefined : `1px solid rgba(168, 85, 247, 0.12)`,
            borderLeftWidth: '2px',
          }}
        >
          <Sparkles size={13} style={{ color: isLight ? 'rgba(126, 34, 206, 0.8)' : undefined, flexShrink: 0 }} />
          <span title={report.autoGeneratedPlatformId ? `平台：${report.autoGeneratedPlatformId}` : undefined}>
            AI 于 {new Date(report.autoGeneratedAt).toLocaleString('zh-CN')} 自动生成（{generationModelLabel}），请审阅后提交
          </span>
        </div>
      )}

      {/* Return reason */}
      {report.returnReason && (
        <div
          className="flex items-center gap-2.5 text-[12px] px-5 py-3 rounded-xl"
          style={{
            color: 'rgba(239, 68, 68, 0.9)',
            background: isLight ? 'rgba(239, 68, 68, 0.04)' : 'rgba(239, 68, 68, 0.06)',
            border: `1px solid ${isLight ? 'rgba(239, 68, 68, 0.20)' : 'rgba(239, 68, 68, 0.12)'}`,
          }}
        >
          退回原因: {report.returnReason}
        </div>
      )}

      {report.status === WeeklyReportStatus.Submitted && (
        <div
          className="flex items-center gap-2.5 text-[12px] px-5 py-3 rounded-xl"
          style={{
            color: isLight ? 'rgba(29, 78, 216, 1)' : 'rgba(59, 130, 246, 0.9)',
            background: isLight ? 'rgba(29, 78, 216, 0.08)' : 'rgba(59, 130, 246, 0.06)',
            border: `1px solid ${isLight ? 'rgba(29, 78, 216, 0.22)' : 'rgba(59, 130, 246, 0.12)'}`,
          }}
        >
          已提交周报在“已审阅”前仍可编辑或删除，变更会即时生效。
        </div>
      )}

      {/* Sections */}
      <div className="flex-1 min-h-0 overflow-auto">
        <div className="flex flex-col gap-5">
          {report.sections.map((section, sIdx) => {
            const theme = sectionThemes[sIdx % sectionThemes.length];
            return (
              <div
                key={sIdx}
                className="rounded-xl overflow-hidden"
                style={{
                  background: isLight ? '#FFFFFF' : 'var(--surface-glass)',
                  backdropFilter: isLight ? undefined : 'blur(12px)',
                  WebkitBackdropFilter: isLight ? undefined : 'blur(12px)',
                  border: isLight ? `1px solid ${theme.border}` : '1px solid var(--border-primary)',
                  borderLeft: isLight ? `3px solid ${theme.color}` : '1px solid var(--border-primary)',
                  boxShadow: isLight ? 'var(--shadow-card-sm)' : undefined,
                }}
              >
                {/* Section header — editorial hairline in light, colored band in dark */}
                <div
                  className="px-5 py-3.5 flex items-center gap-3.5"
                  style={{
                    background: theme.bg,
                    borderBottom: `1px solid ${theme.headerBorder}`,
                  }}
                >
                  <div
                    className="w-7 h-7 rounded-md flex items-center justify-center text-[12px] font-semibold flex-shrink-0"
                    style={{
                      background: theme.badgeBg,
                      color: theme.badgeColor,
                      boxShadow: isLight ? 'none' : `0 2px 8px ${theme.color.replace('0.9', '0.3')}`,
                      fontFamily: isLight ? 'var(--font-serif)' : undefined,
                    }}
                  >
                    {sIdx + 1}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-baseline gap-2">
                      <span
                        className="text-[16px] font-semibold"
                        style={{
                          color: 'var(--text-primary)',
                          fontFamily: isLight ? 'var(--font-serif)' : undefined,
                          letterSpacing: isLight ? '-0.005em' : undefined,
                        }}
                      >
                        {section.templateSection.title}
                      </span>
                      {section.templateSection.isRequired && (
                        <span
                          className="text-[11px]"
                          style={{
                            color: isLight ? 'var(--accent-claude)' : 'rgba(239, 68, 68, 0.8)',
                            fontWeight: 500,
                          }}
                          aria-label="必填"
                          title="必填"
                        >
                          *
                        </span>
                      )}
                    </div>
                    {section.templateSection.description && (
                      <div className="text-[12px] mt-0.5" style={{ color: 'var(--text-muted)' }}>
                        {section.templateSection.description}
                      </div>
                    )}
                  </div>
                  <span className="text-[11px] font-mono" style={{ color: 'var(--text-muted)' }}>
                    {(sections[sIdx]?.items || []).filter(i => i.content.trim()).length} 条
                  </span>
                </div>

                {/* Items */}
                <div className="px-5 py-4 flex flex-col gap-3">
                  {(sections[sIdx]?.items || []).map((item, iIdx) => (
                    <div key={iIdx} className="flex items-start gap-3 group">
                      {section.templateSection.inputType === ReportInputType.BulletList && (
                        <div
                          className="w-2 h-2 rounded-full mt-3 flex-shrink-0"
                          style={{ background: theme.color }}
                        />
                      )}
                      {section.templateSection.inputType === ReportInputType.IssueList ? (
                        <IssueItemCard
                          item={item}
                          categories={section.templateSection.issueCategories ?? []}
                          statuses={section.templateSection.issueStatuses ?? []}
                          canEdit={canEdit}
                          isLight={isLight}
                          themeBorder={theme.border}
                          onChange={(patch) => updateItemFields(sIdx, iIdx, patch)}
                          onPasteImage={(e) => { void handleRichTextPaste(e, sIdx, iIdx); }}
                          pasting={pastingImageKey === `${sIdx}-${iIdx}`}
                        />
                      ) : section.templateSection.inputType === ReportInputType.RichText ? (
                        <div className="flex-1">
                          <textarea
                            className="w-full px-4 py-3 rounded-xl text-[13px] resize-none transition-all duration-200"
                            style={{
                              background: 'var(--bg-secondary)',
                              color: 'var(--text-primary)',
                              border: '1px solid var(--border-primary)',
                              minHeight: 100,
                              outline: 'none',
                            }}
                            onFocus={(e) => { e.currentTarget.style.borderColor = theme.color.replace('0.9', '0.4'); e.currentTarget.style.boxShadow = `0 0 0 2px ${theme.color.replace('0.9', '0.08')}`; }}
                            onBlur={(e) => { e.currentTarget.style.borderColor = 'var(--border-primary)'; e.currentTarget.style.boxShadow = 'none'; }}
                            value={item.content}
                            onChange={(e) => updateItem(sIdx, iIdx, e.target.value)}
                            onPaste={(e) => { void handleRichTextPaste(e, sIdx, iIdx); }}
                            placeholder={pastingImageKey === `${sIdx}-${iIdx}` ? '图片上传中...' : '请输入内容（支持直接粘贴图片，超 5MB 自动压缩）...'}
                            disabled={!canEdit}
                          />
                          {hasMarkdownImage(item.content) && (
                            <RichTextMarkdownContent
                              content={item.content}
                              showRealtimeLabel
                              imageMaxHeight={220}
                              className="mt-2"
                            />
                          )}
                        </div>
                      ) : (
                        <input
                          ref={(el) => { bulletInputRefsRef.current[`${sIdx}:${iIdx}`] = el; }}
                          className="flex-1 px-4 py-3 rounded-xl text-[13px] transition-all duration-200"
                          style={{
                            background: 'var(--bg-secondary)',
                            color: 'var(--text-primary)',
                            border: '1px solid var(--border-primary)',
                            outline: 'none',
                          }}
                          onFocus={(e) => { e.currentTarget.style.borderColor = theme.color.replace('0.9', '0.4'); e.currentTarget.style.boxShadow = `0 0 0 2px ${theme.color.replace('0.9', '0.08')}`; }}
                          onBlur={(e) => { e.currentTarget.style.borderColor = 'var(--border-primary)'; e.currentTarget.style.boxShadow = 'none'; }}
                          value={item.content}
                          onChange={(e) => updateItem(sIdx, iIdx, e.target.value)}
                          onKeyDown={(e) => handleBulletKeyDown(sIdx, iIdx, e)}
                          placeholder="请输入内容，回车新增一条..."
                          disabled={!canEdit}
                        />
                      )}
                      {renderSourceBadge(item.source)}
                      {canEdit && sections[sIdx]?.items.length > 1 && (
                        <button
                          className="p-1.5 rounded-lg opacity-0 group-hover:opacity-100 hover:bg-[rgba(239,68,68,0.08)] transition-all self-center"
                          onClick={() => removeItem(sIdx, iIdx)}
                        >
                          <Trash2 size={13} style={{ color: 'var(--text-muted)' }} />
                        </button>
                      )}
                    </div>
                  ))}
                  {canEdit && (
                    <button
                      className="self-start flex items-center gap-1.5 text-[12px] px-3 py-2 rounded-lg transition-all duration-150"
                      style={{
                        color: theme.color,
                        background: theme.bg,
                        border: `1px dashed ${theme.border}`,
                      }}
                      onClick={() => addItem(sIdx)}
                    >
                      <Plus size={13} /> 添加一条
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

interface AutosaveIndicatorProps {
  status: 'idle' | 'saving' | 'saved' | 'error';
  lastSavedAt: Date | null;
  lastError: string | null;
  onRetry: () => void;
}

function AutosaveIndicator({ status, lastSavedAt, lastError, onRetry }: AutosaveIndicatorProps) {
  if (status === 'saving') {
    return (
      <span
        className="flex items-center gap-1.5 text-[11px] px-2 py-1 rounded-full"
        style={{ color: 'rgba(125, 211, 252, 0.95)', background: 'rgba(56, 189, 248, 0.1)' }}
      >
        <MapSpinner size={12} />
        保存中…
      </span>
    );
  }
  if (status === 'error') {
    return (
      <button
        onClick={onRetry}
        className="flex items-center gap-1.5 text-[11px] px-2 py-1 rounded-full transition-colors"
        style={{ color: 'rgba(248, 113, 113, 0.95)', background: 'rgba(239, 68, 68, 0.1)' }}
        title={lastError || ''}
      >
        <AlertCircle size={12} />
        保存失败，点击重试
      </button>
    );
  }
  if (status === 'saved' && lastSavedAt) {
    const hh = String(lastSavedAt.getHours()).padStart(2, '0');
    const mm = String(lastSavedAt.getMinutes()).padStart(2, '0');
    return (
      <span
        className="flex items-center gap-1.5 text-[11px] px-2 py-1 rounded-full"
        style={{ color: 'rgba(134, 239, 172, 0.9)', background: 'rgba(34, 197, 94, 0.08)' }}
      >
        <Check size={12} />
        已保存 · {hh}:{mm}
      </span>
    );
  }
  return null;
}
