using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;
using MongoDB.Driver;
using PrdAgent.Core.Models;
using PrdAgent.Infrastructure.Database;
using PrdAgent.Infrastructure.LlmGateway;

namespace PrdAgent.Api.Services.ReportAgent;

/// <summary>
/// 周报 AI 生成引擎 — 采集数据 → 构建 Prompt → LLM → 解析 → 保存草稿
/// </summary>
public class ReportGenerationService
{
    private readonly MongoDbContext _db;
    private readonly ILlmGateway _gateway;
    private readonly MapActivityCollector _collector;
    private readonly ILogger<ReportGenerationService> _logger;

    private const string SystemPrompt = """
        你是一位专业的周报撰写助手。你的任务是将原始工作数据整理为清晰、简洁的周报内容。

        规则：
        1. 将多个零散的 Git 提交归纳为有意义的功能/任务描述
        2. 使用业务语言而非技术细节（"完成用户登录模块开发"而非"merge branch feat/login"）
        3. 突出成果和影响，而非过程
        4. 每条不超过 50 字
        5. 对于代码统计数据，只展示关键数字，不做评判
        6. 严格按照模板板块结构输出
        7. 无数据的板块输出空数组
        8. 输出必须是合法的 JSON 格式，不要包含 markdown 代码块标记
        """;

    public ReportGenerationService(
        MongoDbContext db,
        ILlmGateway gateway,
        MapActivityCollector collector,
        ILogger<ReportGenerationService> logger)
    {
        _db = db;
        _gateway = gateway;
        _collector = collector;
        _logger = logger;
    }

    /// <summary>
    /// 为指定用户的指定周期生成周报草稿
    /// </summary>
    public async Task<WeeklyReport> GenerateAsync(
        string userId, string teamId, string templateId,
        int weekYear, int weekNumber, CancellationToken ct)
    {
        // 1. 加载模板
        var template = await _db.ReportTemplates.Find(t => t.Id == templateId).FirstOrDefaultAsync(ct);
        if (template == null)
            throw new InvalidOperationException($"模板 {templateId} 不存在");

        // 2. 计算周期
        var monday = ISOWeek.ToDateTime(weekYear, weekNumber, DayOfWeek.Monday);
        var sunday = monday.AddDays(6).AddHours(23).AddMinutes(59).AddSeconds(59);

        // 3. 采集数据（使用 CancellationToken.None，服务器权威性）
        var activity = await _collector.CollectAsync(userId, monday, sunday, CancellationToken.None);

        // 4. 构建 Prompt
        var userPrompt = BuildUserPrompt(template, activity, weekYear, weekNumber);

        // 5. 调用 LLM（非流式，CancellationToken.None）
        var request = new GatewayRequest
        {
            AppCallerCode = AppCallerRegistry.ReportAgent.Generate.Draft,
            ModelType = ModelTypes.Chat,
            RequestBody = new JsonObject
            {
                ["messages"] = new JsonArray
                {
                    new JsonObject { ["role"] = "system", ["content"] = SystemPrompt },
                    new JsonObject { ["role"] = "user", ["content"] = userPrompt }
                },
                ["temperature"] = 0.3,
                ["max_tokens"] = 4096
            }
        };

        var response = await _gateway.SendAsync(request, CancellationToken.None);

        List<WeeklyReportSection>? generatedSections = null;
        if (response.Success && !string.IsNullOrWhiteSpace(response.Content))
        {
            generatedSections = ParseGeneratedSections(response.Content, template);
        }

        // 6. 如果 LLM 失败或解析失败，回退到空模板
        if (generatedSections == null)
        {
            _logger.LogWarning("AI 生成解析失败，使用空模板。LLM response: {Content}", response.Content?[..Math.Min(200, response.Content?.Length ?? 0)]);
            generatedSections = template.Sections.Select(s => new WeeklyReportSection
            {
                TemplateSection = s,
                Items = new()
            }).ToList();
        }

        // 7. Upsert 周报
        var filter = Builders<WeeklyReport>.Filter.Eq(x => x.UserId, userId)
                   & Builders<WeeklyReport>.Filter.Eq(x => x.TeamId, teamId)
                   & Builders<WeeklyReport>.Filter.Eq(x => x.WeekYear, weekYear)
                   & Builders<WeeklyReport>.Filter.Eq(x => x.WeekNumber, weekNumber);

        var existing = await _db.WeeklyReports.Find(filter).FirstOrDefaultAsync(CancellationToken.None);

        if (existing != null)
        {
            // 更新现有草稿
            var update = Builders<WeeklyReport>.Update
                .Set(x => x.Sections, generatedSections)
                .Set(x => x.AutoGeneratedAt, DateTime.UtcNow)
                .Set(x => x.UpdatedAt, DateTime.UtcNow);

            await _db.WeeklyReports.UpdateOneAsync(filter, update, cancellationToken: CancellationToken.None);
            existing.Sections = generatedSections;
            existing.AutoGeneratedAt = DateTime.UtcNow;
            return existing;
        }
        else
        {
            // 查找用户信息
            var user = await _db.Users.Find(u => u.Id == userId).FirstOrDefaultAsync(CancellationToken.None);
            var team = await _db.ReportTeams.Find(t => t.Id == teamId).FirstOrDefaultAsync(CancellationToken.None);

            var report = new WeeklyReport
            {
                UserId = userId,
                UserName = user?.Name,
                AvatarFileName = user?.AvatarFileName,
                TeamId = teamId,
                TeamName = team?.Name,
                TemplateId = templateId,
                WeekYear = weekYear,
                WeekNumber = weekNumber,
                PeriodStart = monday,
                PeriodEnd = sunday,
                Status = WeeklyReportStatus.Draft,
                Sections = generatedSections,
                AutoGeneratedAt = DateTime.UtcNow
            };

            try
            {
                await _db.WeeklyReports.InsertOneAsync(report, cancellationToken: CancellationToken.None);
            }
            catch (MongoDB.Driver.MongoWriteException ex) when (ex.WriteError?.Category == ServerErrorCategory.DuplicateKey)
            {
                // 并发创建，读取已有记录
                return await _db.WeeklyReports.Find(filter).FirstOrDefaultAsync(CancellationToken.None)
                       ?? report;
            }

            return report;
        }
    }

    private string BuildUserPrompt(ReportTemplate template, CollectedActivity activity, int weekYear, int weekNumber)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"## 周报周期: {weekYear} 年第 {weekNumber} 周");
        sb.AppendLine();

        // 模板结构
        sb.AppendLine("## 模板结构（请严格按此结构输出 JSON）");
        sb.AppendLine("输出格式: { \"sections\": [ { \"items\": [ { \"content\": \"...\", \"source\": \"...\" } ] } ] }");
        sb.AppendLine("sections 数组长度必须与以下板块数量一致。");
        sb.AppendLine();

        for (var i = 0; i < template.Sections.Count; i++)
        {
            var section = template.Sections[i];
            sb.AppendLine($"### 板块 {i + 1}: {section.Title}");
            if (!string.IsNullOrEmpty(section.Description))
                sb.AppendLine($"填写指引: {section.Description}");
            sb.AppendLine($"输入类型: {section.InputType}");
            sb.AppendLine($"是否必填: {(section.IsRequired ? "是" : "否")}");
            if (section.MaxItems.HasValue)
                sb.AppendLine($"最多条目: {section.MaxItems}");
            if (!string.IsNullOrEmpty(section.DataSourceHint))
                sb.AppendLine($"数据来源提示: {section.DataSourceHint}");
            sb.AppendLine();
        }

        // 采集数据
        sb.AppendLine("## 采集到的原始数据");
        sb.AppendLine();

        if (activity.Commits.Count > 0)
        {
            sb.AppendLine("### Git 提交记录");
            foreach (var c in activity.Commits.Take(50))
            {
                sb.AppendLine($"- [{c.CommittedAt:MM-dd}] {c.Message}");
            }
            sb.AppendLine($"总计: {activity.Commits.Count} 次提交");
            var totalAdd = activity.Commits.Sum(c => c.Additions);
            var totalDel = activity.Commits.Sum(c => c.Deletions);
            sb.AppendLine($"代码统计: +{totalAdd} -{totalDel}");
            sb.AppendLine();
        }

        if (activity.DailyLogs.Count > 0)
        {
            sb.AppendLine("### 每日打点");
            foreach (var log in activity.DailyLogs)
            {
                sb.AppendLine($"#### {log.Date:yyyy-MM-dd}");
                foreach (var item in log.Items)
                {
                    var dur = item.DurationMinutes.HasValue ? $" ({item.DurationMinutes}min)" : "";
                    sb.AppendLine($"- [{item.Category}] {item.Content}{dur}");
                }
            }
            sb.AppendLine();
        }

        sb.AppendLine("### 系统活动统计");
        sb.AppendLine($"- PRD 对话会话: {activity.PrdSessions} 次");
        sb.AppendLine($"- 缺陷提交: {activity.DefectsSubmitted} 个");
        sb.AppendLine($"- 视觉创作: {activity.VisualSessions} 次");
        sb.AppendLine($"- AI 调用: {activity.LlmCalls} 次");
        sb.AppendLine();

        sb.AppendLine("请基于以上数据生成周报，每个条目的 source 字段标记来源：git / daily_log / system_activity / ai");

        return sb.ToString();
    }

    private List<WeeklyReportSection>? ParseGeneratedSections(string content, ReportTemplate template)
    {
        try
        {
            // 尝试提取 JSON（可能被 markdown 代码块包裹）
            var json = ExtractJson(content);
            if (string.IsNullOrEmpty(json)) return null;

            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;

            JsonElement sectionsElement;
            if (root.TryGetProperty("sections", out sectionsElement)
                && sectionsElement.ValueKind == JsonValueKind.Array)
            {
                var sections = new List<WeeklyReportSection>();
                var sectionIdx = 0;

                foreach (var sectionJson in sectionsElement.EnumerateArray())
                {
                    var templateSection = sectionIdx < template.Sections.Count
                        ? template.Sections[sectionIdx]
                        : new ReportTemplateSection { Title = $"板块 {sectionIdx + 1}" };

                    var items = new List<WeeklyReportItem>();

                    if (sectionJson.TryGetProperty("items", out var itemsArray)
                        && itemsArray.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var itemJson in itemsArray.EnumerateArray())
                        {
                            var itemContent = itemJson.TryGetProperty("content", out var c)
                                ? c.GetString() ?? ""
                                : "";
                            var source = itemJson.TryGetProperty("source", out var s)
                                ? s.GetString() ?? "ai"
                                : "ai";

                            if (!string.IsNullOrWhiteSpace(itemContent))
                            {
                                items.Add(new WeeklyReportItem
                                {
                                    Content = itemContent,
                                    Source = source
                                });
                            }
                        }
                    }

                    sections.Add(new WeeklyReportSection
                    {
                        TemplateSection = templateSection,
                        Items = items
                    });

                    sectionIdx++;
                }

                // 补齐缺失的板块
                while (sections.Count < template.Sections.Count)
                {
                    sections.Add(new WeeklyReportSection
                    {
                        TemplateSection = template.Sections[sections.Count],
                        Items = new()
                    });
                }

                return sections;
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "解析 AI 生成的周报内容失败");
        }

        return null;
    }

    private static string? ExtractJson(string content)
    {
        // 尝试直接解析
        content = content.Trim();
        if (content.StartsWith('{'))
            return content;

        // 尝试从 markdown 代码块中提取
        var jsonStart = content.IndexOf("```json", StringComparison.OrdinalIgnoreCase);
        if (jsonStart >= 0)
        {
            var start = content.IndexOf('\n', jsonStart) + 1;
            var end = content.IndexOf("```", start, StringComparison.Ordinal);
            if (end > start)
                return content[start..end].Trim();
        }

        // 尝试找到第一个 { 和最后一个 }
        var firstBrace = content.IndexOf('{');
        var lastBrace = content.LastIndexOf('}');
        if (firstBrace >= 0 && lastBrace > firstBrace)
            return content[firstBrace..(lastBrace + 1)];

        return null;
    }
}
