/**
 * 公共藏书阁 —— 书目 SSOT（七卷）
 *
 * 编排原则（不是「程序员必读 50 本」那种平铺书单）：
 *  1. 按**心路历程**分卷：从「代码能跑」到「能替别人兜底」，每卷是一次身份升级。
 *  2. 每卷钉一句**团队真实卡住的处境**（painQuote），读者一眼认出「这说的就是我」。
 *  3. 每本书的 why 必须回答「它治这一卷的什么病」，禁止写「经典必读」这类空话。
 *  4. takeaway 是**动作**不是感受：读完能做出什么可验证的行为改变。
 *
 * 书目均为公开出版物，书名与作者按中译本通行译名登记；不编造 ISBN、页码、
 * 销量等无法核实的字段（.claude/rules/no-rootless-tree.md）。
 */
import type { PainRemedy, Volume } from './types';

export const VOLUMES: Volume[] = [
  {
    id: 'vol-boot',
    index: 1,
    name: '开机',
    subtitle: '先把话说清楚，再把活干完',
    icon: 'Power',
    painQuote: '新人刚进来就被推去出方案，业务还没摸清。',
    cure: '新人最先缺的不是技术，是「把问题定义清楚」和「把事情做完」的习惯。这一卷让你在动手前先问对问题，动手后能自己收尾。',
    books: [
      {
        id: 'b-lamp',
        title: '你的灯亮着吗？',
        original: 'Are Your Lights On?',
        author: 'Donald C. Gause、Gerald M. Weinberg',
        track: 'both',
        level: 1,
        why: '不熟业务流程就被推去出方案，根子是拿到需求直接想解法、从没确认过问题是什么、谁的问题。这本书整本都在训练这一步。',
        takeaway: '接需求先答三问：问题是谁的、真正困扰是什么、不解决会怎样。答不上来就不动手。',
      },
      {
        id: 'b-pragmatic',
        title: '程序员修炼之道：通向务实的最高境界',
        original: 'The Pragmatic Programmer',
        author: 'Andrew Hunt、David Thomas',
        track: 'dev',
        level: 1,
        why: '职业习惯的总纲：不重复自己、正交设计、曳光弹开发、对自己的代码负责。新人和老手的差距大半在这些习惯上，不在语法。',
        takeaway: '给每次改动留下可追溯的痕迹，不再出现「这段谁写的、为什么这么写」没人答得上来。',
      },
      {
        id: 'b-clean-code',
        title: '代码整洁之道',
        original: 'Clean Code',
        author: 'Robert C. Martin',
        track: 'dev',
        level: 1,
        why: '代码规范没人讲清楚时的最低共识线。命名、函数长度、注释该写什么，先有一套共同语言，评审才有得聊。',
        takeaway: '能说出一段代码「差在哪」，而不只是「我觉得不太好」。',
      },
      {
        id: 'b-how-computer-runs',
        title: '计算机是怎样跑起来的',
        author: '矢泽久雄',
        track: 'both',
        level: 1,
        why: '给非科班和产品经理补底：CPU、内存、网络到底在做什么。听得懂开发说的话，才提得出做得了的需求。',
        takeaway: '产品经理能判断一个需求是「改文案」还是「动底层」，不再一律当成一样贵。',
      },
      {
        id: 'b-productive-programmer',
        title: '卓有成效的程序员',
        original: 'The Productive Programmer',
        author: 'Neal Ford',
        track: 'dev',
        level: 1,
        why: '把重复劳动自动化掉。新人耗在手工搭环境、手工验证上的时间，正是赶工期时最先被牺牲的质量预算。',
        takeaway: '把自己每天重复三次以上的操作变成脚本或快捷键。',
      },
    ],
  },
  {
    id: 'vol-rules',
    index: 2,
    name: '立规矩',
    subtitle: '代码规范、构建发布、交付纪律',
    icon: 'Ruler',
    painQuote: '代码规范、构建、发布都没人讲，全靠自己摸索。',
    cure: '规范不是写在文档里给人背的，是嵌进流水线里自动执行的。这一卷讲的是怎么把「口头约定」变成「不遵守就过不了」。',
    books: [
      {
        id: 'b-swe-at-google',
        title: 'Google 软件工程',
        original: 'Software Engineering at Google',
        author: 'Titus Winters、Tom Manshreck、Hyrum Wright',
        track: 'both',
        level: 2,
        why: '本卷第一本。它正面回答「几千人改同一个仓库怎么不乱」：代码评审为什么必须做、规范为什么要工具化、大规模变更怎么推。你们现在遇到的每一个协作问题，它都写过。',
        takeaway: '能论证「代码评审不是走过场」，并说得出一次有效评审该看什么、不该看什么。',
      },
      {
        id: 'b-continuous-delivery',
        title: '持续交付：发布可靠软件的系统方法',
        original: 'Continuous Delivery',
        author: 'Jez Humble、David Farley',
        track: 'dev',
        level: 2,
        why: '构建发布没人讲清楚时，正解不是写一篇发布手册，是把发布做成任何人按一下就能跑、跑挂了能自动退回去的流水线。',
        takeaway: '说得出本项目从提交到上线经过哪几道闸，每道闸拦的是什么。',
      },
      {
        id: 'b-cd-2',
        title: '持续交付 2.0：业务引领的 DevOps 精要',
        author: '乔梁',
        track: 'both',
        level: 2,
        why: '中文语境下的落地版，讲的是国内团队真实的组织阻力与分阶段推进路径，比直接照搬更容易在自家团队跑起来。',
        takeaway: '能给自己团队排出一张「先补哪道闸」的改进顺序表。',
      },
      {
        id: 'b-phoenix',
        title: '凤凰项目：一个 IT 运维的传奇故事',
        original: 'The Phoenix Project',
        author: 'Gene Kim、Kevin Behr、George Spafford',
        track: 'both',
        level: 1,
        why: '小说体，一晚上能读完。讲的就是一个赶工期、到处救火、谁都不敢改的团队怎么一步步爬出来，最适合拿给不写代码的领导看。',
        takeaway: '识别出团队里真正的瓶颈工序，而不是让所有人一起加班。',
      },
      {
        id: 'b-devops-handbook',
        title: 'DevOps 实践指南',
        original: 'The DevOps Handbook',
        author: 'Gene Kim、Jez Humble、Patrick Debois、John Willis',
        track: 'dev',
        level: 2,
        why: '《凤凰项目》的操作手册版。前一本让你信，这一本告诉你具体怎么做。',
        takeaway: '把一条手工发布流程改造成可重复、可回滚的自动流程。',
      },
      {
        id: 'b-code-complete',
        title: '代码大全（第 2 版）',
        original: 'Code Complete',
        author: 'Steve McConnell',
        track: 'dev',
        level: 2,
        why: '构造活动的百科全书。规范争论不下时，它是那本能拿出来当裁判的书。',
        takeaway: '评审时给得出依据，而不是靠职级压人。',
      },
      {
        id: 'b-unix-art',
        title: 'Unix 编程艺术',
        original: 'The Art of Unix Programming',
        author: 'Eric S. Raymond',
        track: 'dev',
        level: 2,
        why: '规范背后的价值观：清晰、组合、最小惊讶。知道规矩为什么这么定，才不会一边遵守一边阳奉阴违。',
        takeaway: '写出让下一个人不用问你就敢改的代码。',
      },
    ],
  },
  {
    id: 'vol-domain',
    index: 3,
    name: '懂业务',
    subtitle: '领域、需求、真实流程',
    icon: 'Compass',
    painQuote: '赶工期，核心业务流程还没吃透就开始动手。',
    cure: '不熟业务的人写出来的代码，每一行都是猜的。这一卷教你怎么把业务装进脑子、装进模型、再装进代码，而不是靠口口相传。',
    books: [
      {
        id: 'b-ddd',
        title: '领域驱动设计：软件核心复杂性应对之道',
        original: 'Domain-Driven Design',
        author: 'Eric Evans',
        track: 'both',
        level: 3,
        why: '这本书的核心主张就是「代码里的名词必须和业务嘴里的名词是同一个」。做不到这点，新人永远得靠追着老人问才能干活。',
        takeaway: '建立团队统一语言，让同一条业务流程在文档、会议和代码里是同一个词、同一个含义。',
      },
      {
        id: 'b-ddd-distilled',
        title: '领域驱动设计精粹',
        original: 'Domain-Driven Design Distilled',
        author: 'Vaughn Vernon',
        track: 'both',
        level: 1,
        why: '上一本太厚，这本两百页讲完要点。产品经理也读得动，适合当团队共读的第一本。',
        takeaway: '用事件风暴把一条业务流程在白板上还原出来，新人当场就能看懂。',
      },
      {
        id: 'b-implementing-ddd',
        title: '实现领域驱动设计',
        original: 'Implementing Domain-Driven Design',
        author: 'Vaughn Vernon',
        track: 'dev',
        level: 3,
        why: '从概念落到代码：聚合怎么划、边界怎么定。这一步做对了，才有下一卷「改底层不炸别人」的可能。',
        takeaway: '划出限界上下文，明确哪些改动会跨界、必须先打招呼。',
      },
      {
        id: 'b-ddd-cn',
        title: '解构领域驱动设计',
        author: '张逸',
        track: 'dev',
        level: 3,
        why: '中文原创、案例贴近国内业务，把 DDD 从「听起来很美」拆成可执行的步骤。',
        takeaway: '把一个真实业务模块按限界上下文重新划一遍并说清依据。',
      },
      {
        id: 'b-story-mapping',
        title: '用户故事地图',
        original: 'User Story Mapping',
        author: 'Jeff Patton',
        track: 'pm',
        level: 1,
        why: '需求碎成一堆卡片时，没人看得见整条流程。故事地图把整条业务流程摊成一张图，谁不熟一眼就补得上。',
        takeaway: '用一张故事地图代替口头交底，新人自己就能看出流程缺口。',
      },
      {
        id: 'b-inspired',
        title: '启示录：打造用户喜爱的产品',
        original: 'Inspired',
        author: 'Marty Cagan',
        track: 'pm',
        level: 2,
        why: '讲产品经理该负什么责：不是传话筒，是要为「这个需求值不值得做」负责。一味赶工的根源常常是没人做过这一步。',
        takeaway: '在排期前先给出「不做会怎样」的判断，砍掉真正不该做的需求。',
      },
    ],
  },
  {
    id: 'vol-design',
    index: 4,
    name: '会设计',
    subtitle: '边界、契约，改底层不炸别人',
    icon: 'Blocks',
    painQuote: '几个人同时在改，有人动了底层，别处就跟着出问题。',
    cure: '互相踩踏不是人品问题，是边界问题。这一卷讲怎么把系统切成「你改你的、我改我的」，以及必须共享时怎么用契约兜住。',
    books: [
      {
        id: 'b-clean-arch',
        title: '架构整洁之道',
        original: 'Clean Architecture',
        author: 'Robert C. Martin',
        track: 'dev',
        level: 2,
        why: '本卷第一本。它只讲一件事：依赖该往哪个方向指。方向对了，改底层才不会顺着依赖链把上层全炸掉。',
        takeaway: '画出本项目的依赖方向图，指出哪几条是反向依赖、正是踩踏高发处。',
      },
      {
        id: 'b-ddia',
        title: '数据密集型应用系统设计',
        original: 'Designing Data-Intensive Applications',
        author: 'Martin Kleppmann',
        track: 'dev',
        level: 3,
        why: '数据是最难改也最容易牵连所有人的那一层。这本书讲清楚了改动数据模型的代价从哪来。',
        takeaway: '评估一次表结构变更的爆炸半径，而不是改完再看谁报错。',
      },
      {
        id: 'b-release-it',
        title: '发布！设计与部署稳定的分布式系统',
        original: 'Release It!',
        author: 'Michael T. Nygard',
        track: 'dev',
        level: 2,
        why: '专讲「一改我这边就出问题」的工程解法：舱壁、熔断、超时。让别人的故障不变成你的故障。',
        takeaway: '给关键依赖加上超时与降级，别人挂了自己还能活。',
      },
      {
        id: 'b-poeaa',
        title: '企业应用架构模式',
        original: 'Patterns of Enterprise Application Architecture',
        author: 'Martin Fowler',
        track: 'dev',
        level: 3,
        why: '给常见结构起了共同的名字。评审时能说「这里该用仓储」，比说「我觉得应该抽一层」有效得多。',
        takeaway: '用模式名沟通设计，减少评审里的车轱辘话。',
      },
      {
        id: 'b-microservices-patterns',
        title: '微服务架构设计模式',
        original: 'Microservices Patterns',
        author: 'Chris Richardson',
        track: 'dev',
        level: 3,
        why: '拆分不是万灵药。这本书把每个拆分决策的代价摆出来，避免为了「解耦」制造更多跨团队协调。',
        takeaway: '判断一个模块该拆还是该合，说得出代价而不只是好处。',
      },
      {
        id: 'b-evolutionary-arch',
        title: '演进式架构',
        original: 'Building Evolutionary Architectures',
        author: 'Neal Ford、Rebecca Parsons、Patrick Kua',
        track: 'dev',
        level: 3,
        why: '提出「架构适应度函数」：把架构约束写成会自动跑红的测试。这正是治「有人改了底层没人知道」的机械手段。',
        takeaway: '给关键架构约束写一条会变红的守卫测试，而不是写进文档指望人记得。',
      },
      {
        id: 'b-just-enough-arch',
        title: '恰如其分的软件架构',
        original: 'Just Enough Software Architecture',
        author: 'George Fairbanks',
        track: 'dev',
        level: 3,
        why: '按风险决定设计投入多少，治「过度设计」和「完全不设计」两个极端。赶工期时尤其需要这把尺子。',
        takeaway: '按风险给设计投入定档，在赶工时也知道哪里不能省。',
      },
      {
        id: 'b-thinking-in-systems',
        title: '系统之美',
        original: 'Thinking in Systems',
        author: 'Donella H. Meadows',
        track: 'both',
        level: 2,
        why: '跳出代码看系统：为什么按下葫芦浮起瓢、为什么局部优化会让整体变差。产品经理和技术负责人都该读。',
        takeaway: '找出团队里那个「越努力越糟」的反馈回路并把它掐断。',
      },
    ],
  },
  {
    id: 'vol-review',
    index: 5,
    name: '能审人',
    subtitle: '评审、测试、重构、接手烂摊子',
    icon: 'ShieldCheck',
    painQuote: '评审排给了看不出问题的人，于是只剩下机械检查，成了走过场。',
    cure: '审不出问题不是能力问题，是缺方法：没有检查清单、没有可自动化的部分、没有明确的评审目标。这一卷把评审从玄学变成手艺。',
    books: [
      {
        id: 'b-refactoring',
        title: '重构：改善既有代码的设计（第 2 版）',
        original: 'Refactoring',
        author: 'Martin Fowler',
        track: 'dev',
        level: 2,
        why: '本卷第一本。它给了一整套「坏味道」词汇表——评审时你终于能指着代码说出它到底哪里不对，而不是「感觉有点乱」。',
        takeaway: '评审意见能落到具体坏味道和具体手法上，作者照着就能改。',
      },
      {
        id: 'b-legacy-code',
        title: '修改代码的艺术',
        original: 'Working Effectively with Legacy Code',
        author: 'Michael C. Feathers',
        track: 'dev',
        level: 3,
        why: '专治「项目改得太乱我都不想看了」。教你怎么在没有测试的烂摊子里安全地下第一刀。',
        takeaway: '在没有测试的老代码上，先建立接缝再改动，而不是硬改后祈祷。',
      },
      {
        id: 'b-tdd',
        title: '测试驱动开发',
        original: 'Test-Driven Development: By Example',
        author: 'Kent Beck',
        track: 'dev',
        level: 2,
        why: '评审看不出的问题，测试能拦住。把「人眼审」换成「机器审」，人才有精力去看真正需要判断的设计问题。',
        takeaway: '提交前让机器把明显问题拦掉，评审只留给人类判断题。',
      },
      {
        id: 'b-google-test',
        title: 'Google 测试之道',
        original: 'How Google Tests Software',
        author: 'James Whittaker、Jason Arbon、Jeff Carollo',
        track: 'both',
        level: 2,
        why: '回答「质量该谁负责」。如果质量只靠最后一道人工审查，那这道审查一定形同虚设。',
        takeaway: '把质量责任前移到写代码的人，评审不再是唯一防线。',
      },
      {
        id: 'b-unit-testing-art',
        title: '单元测试的艺术',
        original: 'The Art of Unit Testing',
        author: 'Roy Osherove',
        track: 'dev',
        level: 2,
        why: '讲怎么写出「改坏了会红、改对了不会红」的测试。测试写不对，绿灯反而会骗人。',
        takeaway: '判断一条测试是真在防守，还是只是陪着一起绿。',
      },
      {
        id: 'b-clean-coder',
        title: '程序员的职业素养',
        original: 'The Clean Coder',
        author: 'Robert C. Martin',
        track: 'dev',
        level: 1,
        why: '正面讲赶工期时怎么办：怎么说不、怎么给估算、怎么在压力下守住底线。被反复消耗的人尤其该读。',
        takeaway: '面对不合理排期时给得出有依据的反馈，而不是默默接下再默默崩。',
      },
      {
        id: 'b-mythical-man-month',
        title: '人月神话',
        original: 'The Mythical Man-Month',
        author: 'Frederick P. Brooks',
        track: 'both',
        level: 2,
        why: '五十年前就写清楚了：往晚了的项目加人只会更晚。「找个新人来赶工」为什么常常帮倒忙，答案在这里。',
        takeaway: '在项目落后时选对策略，而不是本能地加人。',
      },
      {
        id: 'b-peopleware',
        title: '人件',
        original: 'Peopleware',
        author: 'Tom DeMarco、Timothy Lister',
        track: 'both',
        level: 1,
        why: '疲惫感是可以被管理的工程变量。这本书讲的是环境与组织怎么系统性地毁掉或保住团队的产出。',
        takeaway: '识别出团队里正在消耗人的那几个结构性问题，并说得出改法。',
      },
    ],
  },
  {
    id: 'vol-ai',
    index: 6,
    name: '驭 AI',
    subtitle: '看懂它、用好它、审得住它',
    icon: 'Cpu',
    painQuote: '赶进度的时候，AI 生成的代码没人细看就合了进去。',
    cure: 'AI 不会因为你不看就写对。这一卷分两段：先建立起对模型能力与边界的真实认知，再学会怎么把 AI 产出纳入和人一样的质量闸门。',
    books: [
      {
        id: 'b-wolfram-chatgpt',
        title: '这就是 ChatGPT',
        original: 'What Is ChatGPT Doing... and Why Does It Work?',
        author: 'Stephen Wolfram',
        track: 'both',
        level: 1,
        why: '本卷第一本，一百多页。知道它本质上在做下一个词的概率预测，就明白它为什么会一本正经地乱写——这不是 bug，是机制。',
        takeaway: '预判 AI 在哪类任务上必然不可靠，提前安排人工核验点。',
      },
      {
        id: 'b-co-intelligence',
        title: '共同智能：与 AI 一起生活和工作',
        original: 'Co-Intelligence: Living and Working with AI',
        author: 'Ethan Mollick',
        track: 'both',
        level: 1,
        why: '沃顿商学院教授拿大量真实工作场景做的实验记录。它回答的不是「AI 能不能干这活」，而是「哪些活该交出去、交出去之后人还得守住什么」——正对着「交出去就不看了」这件事。',
        takeaway: '划出自己岗位上哪几类任务可以交给 AI、哪几类必须人来定稿，并说得出各自的理由。',
      },
      {
        id: 'b-prompt-eng-llm',
        title: 'Prompt Engineering for LLMs',
        author: 'John Berryman、Albert Ziegler',
        track: 'both',
        level: 2,
        why: '作者之一是 GitHub Copilot 早期的核心研究员，讲的是「模型看到了什么，才写出了这个」。AI 乱写有一大半是上下文没给够，不是模型笨——这部分是你能控制的。',
        takeaway: '让 AI 动手前先把约束、现有代码和验收标准一起喂进去，把返工从事后审查挪到事前。',
      },
      {
        id: 'b-ai-engineering',
        title: 'AI Engineering',
        author: 'Chip Huyen',
        track: 'dev',
        level: 2,
        why: '讲基础模型落到生产上的那一层：评估集怎么建、护栏怎么设、什么时候该直接拒绝模型的输出。「这次生成靠不靠谱」在这本书里是个工程问题，有答案。',
        takeaway: '给 AI 参与的环节配一套能自动跑的评估与拒绝策略，让「靠不靠谱」变成一个能读的数字。',
      },
      {
        id: 'b-code-reading',
        title: '代码阅读方法与实践',
        original: 'Code Reading: The Open Source Perspective',
        author: 'Diomidis Spinellis',
        track: 'dev',
        level: 2,
        why: '审不出问题的根子往往不是不懂业务，是没系统练过读代码。这本书把读代码当成一门可训练的手艺：从哪儿下口、怎么顺着数据流走、怎么在不跑起来的情况下判断一段逻辑对不对。',
        takeaway: '面对一段不是自己写的代码，能按固定顺序读出它的控制流与边界，指得出哪里可能出问题。',
      },
      {
        id: 'b-crime-scene',
        title: '你的代码就是犯罪现场',
        original: 'Your Code as a Crime Scene',
        author: 'Adam Tornhill',
        track: 'dev',
        level: 2,
        why: '用版本库的历史数据找出真正该管的地方：哪些文件改得最频繁、哪些模块总是被一起改、谁动了之后别人最常出问题。把「项目改得很乱」这种体感变成一张能指着看的图。',
        takeaway: '从 git 历史算出热点文件与隐性耦合，用数据决定先重构哪一块、哪一块必须两个人一起改。',
      },
      {
        id: 'b-dive-into-dl',
        title: '动手学深度学习',
        original: 'Dive into Deep Learning',
        author: '阿斯顿·张、李沐、扎卡里·立顿、亚历山大·斯莫拉',
        track: 'dev',
        level: 2,
        why: '中文社区最好的入门实践书，代码可跑。想从「会用 API」进到「知道里面发生了什么」，从这本开始。',
        takeaway: '看懂模型训练与推理的基本流程，能判断一个 AI 需求的技术可行性。',
      },
      {
        id: 'b-llm-cn',
        title: '大规模语言模型：从理论到实践',
        author: '张奇、桂韬、郑锐、黄萱菁',
        track: 'dev',
        level: 3,
        why: '系统讲预训练、微调、对齐与推理。要在业务里落地大模型能力，这是绕不开的知识底盘。',
        takeaway: '判断一个场景该用提示工程、检索增强还是微调，而不是一律硬塞提示词。',
      },
      {
        id: 'b-designing-ml-systems',
        title: '设计机器学习系统',
        original: 'Designing Machine Learning Systems',
        author: 'Chip Huyen',
        track: 'dev',
        level: 3,
        why: '讲的是 AI 功能作为**系统**怎么设计：数据、评估、监控、迭代。模型只是其中一小块，工程才是大头。',
        takeaway: '为 AI 功能设计出可评估、可回归的验收方式，而不是靠人肉试几次觉得还行。',
      },
      {
        id: 'b-aima',
        title: '人工智能：现代方法',
        original: 'Artificial Intelligence: A Modern Approach',
        author: 'Stuart Russell、Peter Norvig',
        track: 'dev',
        level: 3,
        why: '工具书。想知道当前这波之外还有什么，或需要一个权威定义时来查。不必通读。',
        takeaway: '在概念混乱的讨论里给出准确定义，避免把营销词当技术词用。',
      },
      {
        id: 'b-deep-learning',
        title: '深度学习',
        original: 'Deep Learning',
        author: 'Ian Goodfellow、Yoshua Bengio、Aaron Courville',
        track: 'dev',
        level: 3,
        why: '理论底座。想真正读懂论文而不是只读解读文章时，这本绕不过去。',
        takeaway: '具备读一手论文的数学基础。',
      },
    ],
  },
  {
    id: 'vol-stage',
    index: 7,
    name: '上台面',
    subtitle: '表达、判断、带人',
    icon: 'Presentation',
    painQuote: '明知道评审安排得不对，却说不清该怎么改、找谁改。',
    cure: '技术做到一定程度，卡住你的是「说不清楚」和「推不动」。这一卷讲怎么把判断讲成别人能接受的话，以及怎么让规矩在组织里真正生效。',
    books: [
      {
        id: 'b-pyramid',
        title: '金字塔原理',
        original: 'The Minto Pyramid Principle',
        author: 'Barbara Minto',
        track: 'both',
        level: 1,
        why: '本卷第一本。结论先行、归类分组。同样的意见，用它的结构说出来，才有人听得进去、推得动。',
        takeaway: '汇报和评审意见都先给结论，让对方三十秒内知道你要什么。',
      },
      {
        id: 'b-nvc',
        title: '非暴力沟通',
        original: 'Nonviolent Communication',
        author: 'Marshall B. Rosenberg',
        track: 'both',
        level: 1,
        why: '评审意见最容易被听成人身攻击。这本书教你把「你这写得不行」换成对方愿意接的说法。',
        takeaway: '把评审意见落在事实与影响上，减少无谓对抗。',
      },
      {
        id: 'b-yujun',
        title: '俞军产品方法论',
        author: '俞军',
        track: 'pm',
        level: 2,
        why: '中文语境下最成体系的产品判断框架：用户价值、交易成本、决策模型。治「需求全靠拍脑袋」。',
        takeaway: '用一致的框架解释为什么做这个、不做那个。',
      },
      {
        id: 'b-lean-startup',
        title: '精益创业',
        original: 'The Lean Startup',
        author: 'Eric Ries',
        track: 'pm',
        level: 1,
        why: '赶着先做出来有时是对的——前提是你在验证假设，而不是在赌。这本书教你区分这两者。',
        takeaway: '把赶工做成一次有明确验证目标的实验，而不是无差别加速。',
      },
      {
        id: 'b-effective-executive',
        title: '卓有成效的管理者',
        original: 'The Effective Executive',
        author: 'Peter F. Drucker',
        track: 'both',
        level: 2,
        why: '讲怎么把有限精力放在真正有贡献的地方。技术负责人从「自己干」转向「让别人干得好」时必读。',
        takeaway: '分清哪些事必须自己做、哪些该建机制让别人做对。',
      },
      {
        id: 'b-team-of-teams',
        title: '赋能：打造应对不确定性的敏捷团队',
        original: 'Team of Teams',
        author: 'Stanley McChrystal',
        track: 'both',
        level: 2,
        why: '讲怎么让信息在团队间流动、让决策下沉。没人告诉你该怎么做，本质就是信息流动失败。',
        takeaway: '设计出让上下文自动到达执行者的机制，而不是靠人主动问。',
      },
    ],
  },
];

/**
 * 痛点药方表 —— 藏书阁的入口。
 *
 * 这些是团队里真实发生过的处境。写的是症状不是某个人的原话——
 * 抱怨出自具体的人，页面是全员可见的，逐字挂上去等于把人架在那儿。
 * 转述成处境既留住「说的就是我」的共鸣，也不让任何人对号入座。每一条都要
 * 指向一卷能治它的书，让人不必先读完整个书单才知道自己该从哪进。
 */
export const PAIN_REMEDIES: PainRemedy[] = [
  {
    quote: '代码规范、构建发布，没人告诉我该怎么做',
    diagnosis: '上下文没有随任务一起交付；规范停在口头，没有嵌进流水线。',
    volumeId: 'vol-rules',
  },
  {
    quote: '问题堆到最后一道人工闸才被发现',
    diagnosis: '质量责任压在最后一道人工闸上，前面几道闸根本不存在。',
    volumeId: 'vol-review',
  },
  {
    quote: '不熟业务的人被推去出方案',
    diagnosis: '业务知识靠口口相传，没有沉淀成人人可读的模型与流程图。',
    volumeId: 'vol-domain',
  },
  {
    quote: 'AI 生成的代码没人细看就合进去了',
    diagnosis: 'AI 产出没有被纳入和人类代码同一套质量闸门。',
    volumeId: 'vol-ai',
  },
  {
    quote: '几个人同时改，一动底层别处就出问题',
    diagnosis: '模块边界不清、依赖方向混乱，没有会自动报警的架构约束。',
    volumeId: 'vol-design',
  },
  {
    quote: '评审只剩机械检查，那还审什么',
    diagnosis: '评审目标没定义。能机械检查的没交给机器，需要判断的没人看。',
    volumeId: 'vol-review',
  },
  {
    quote: '代码越改越乱，不想再打开',
    diagnosis: '缺少在无测试的遗留代码上安全动刀的方法，于是越改越怕、越怕越乱。',
    volumeId: 'vol-review',
  },
  {
    quote: '评审派给了看不出问题的人',
    diagnosis: '评审的角色与标准没有共识，说不清楚就推不动。',
    volumeId: 'vol-stage',
  },
];

/** 全部书目拍平，供搜索与统计使用。 */
export const ALL_BOOKS = VOLUMES.flatMap((v) => v.books.map((b) => ({ ...b, volumeId: v.id })));

export function findVolume(id: string): Volume | undefined {
  return VOLUMES.find((v) => v.id === id);
}
