import { useMemo, useRef, useState } from 'react';
import { X, Download, Copy, Check, FileText, Code, Eye, Table2, ChevronDown, ExternalLink, Maximize2, Minimize2, Bot } from 'lucide-react';
import type { ExecutionArtifact } from '@/services/contracts/workflowAgent';

interface ArtifactPreviewModalProps {
  artifact: ExecutionArtifact;
  onClose: () => void;
}

// ═══════════════════════════════════════════════════════════════
// 内容嗅探：基于实际内容推断真实类型，不盲信 mimeType
// ═══════════════════════════════════════════════════════════════

type DetectedType = 'html' | 'json' | 'markdown' | 'csv' | 'image' | 'text';

function sniffContentType(content: string, originalMime: string, name: string): DetectedType {
  if (!content) return 'text';

  // 文件名后缀优先（如果有明确后缀且与内容一致）
  const ext = name.match(/\.(\w+)$/)?.[1]?.toLowerCase();

  const trimmed = content.trimStart();

  // HTML：DOCTYPE 或 <html 开头
  if (/^<!doctype\s+html/i.test(trimmed) || /^<html[\s>]/i.test(trimmed))
    return 'html';

  // HTML 片段：以 < 开头且包含常见 HTML 标签
  if (trimmed.startsWith('<') && /<(?:div|table|p|body|head|style|section|h[1-6]|ul|ol|li|span|a\s)/i.test(trimmed))
    return 'html';

  // JSON
  if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
    try { JSON.parse(content); return 'json'; } catch { /* not valid JSON */ }
  }

  // Image data URI
  if (trimmed.startsWith('data:image/'))
    return 'image';

  // CSV：前两行逗号数一致且 >= 2
  if (!trimmed.startsWith('#') && !trimmed.startsWith('<')) {
    const lines = trimmed.split('\n', 3);
    if (lines.length >= 2) {
      const c1 = (lines[0].match(/,/g) || []).length;
      const c2 = (lines[1].match(/,/g) || []).length;
      if (c1 >= 2 && c1 === c2) return 'csv';
    }
  }

  // Markdown
  if (ext === 'md' || originalMime === 'text/markdown') return 'markdown';
  if (/^#{1,6}\s/.test(trimmed) || /\n#{1,6}\s/.test(content) || /\n\|[^|]+\|/.test(content))
    return 'markdown';

  // 回退到 mimeType
  if (originalMime.includes('html')) return 'html';
  if (originalMime.includes('json')) return 'json';
  if (originalMime.includes('markdown')) return 'markdown';
  if (originalMime.includes('csv')) return 'csv';
  if (originalMime.includes('image')) return 'image';

  return 'text';
}

/** 根据检测到的类型返回对应的 MIME */
function detectedTypeToMime(dt: DetectedType): string {
  const map: Record<DetectedType, string> = {
    html: 'text/html', json: 'application/json', markdown: 'text/markdown',
    csv: 'text/csv', image: 'image/png', text: 'text/plain',
  };
  return map[dt];
}

const TYPE_LABELS: Record<DetectedType, string> = {
  html: 'HTML', json: 'JSON', markdown: 'Markdown', csv: 'CSV', image: '图片', text: '纯文本',
};

// ═══════════════════════════════════════════════════════════════
// 主组件
// ═══════════════════════════════════════════════════════════════

export function ArtifactPreviewModal({ artifact, onClose }: ArtifactPreviewModalProps) {
  const [copied, setCopied] = useState(false);
  const [viewMode, setViewMode] = useState<'preview' | 'raw'>('preview');
  const [downloadMenuOpen, setDownloadMenuOpen] = useState(false);
  const [iframeFullscreen, setIframeFullscreen] = useState(false);
  const iframeRef = useRef<HTMLIFrameElement>(null);

  const content = artifact.inlineContent || '';
  const isAutoGenerated = artifact.tags?.includes('auto-generated');

  // 核心：内容嗅探，自动检测真实类型
  const detectedType = useMemo(
    () => sniffContentType(content, artifact.mimeType, artifact.name),
    [content, artifact.mimeType, artifact.name]
  );

  const effectiveMime = detectedTypeToMime(detectedType);
  const mimeOverridden = effectiveMime !== artifact.mimeType;

  const isHtml = detectedType === 'html';
  const isJson = detectedType === 'json';
  const isMarkdown = detectedType === 'markdown';
  const isCsv = detectedType === 'csv';
  const isImage = detectedType === 'image';
  const isFullHtmlPage = isHtml && /<!doctype\s+html|<html[\s>]/i.test(content.slice(0, 200));

  // JSON 数组 → 表格
  const jsonArray = useMemo<Record<string, unknown>[] | null>(() => {
    if (!isJson || !content) return null;
    try {
      const parsed = JSON.parse(content);
      if (Array.isArray(parsed) && parsed.length > 0 && typeof parsed[0] === 'object' && parsed[0] !== null)
        return parsed as Record<string, unknown>[];
    } catch { /* ignore */ }
    return null;
  }, [content, isJson]);

  // CSV → 表格
  const csvData = useMemo<{ columns: string[]; rows: string[][] } | null>(() => {
    if (!isCsv || !content) return null;
    const lines = content.trim().split('\n');
    if (lines.length < 2) return null;
    const columns = parseCsvLine(lines[0]);
    const rows = lines.slice(1).map(parseCsvLine);
    return { columns, rows };
  }, [content, isCsv]);

  // 表格列：从 JSON 数组提取
  const columns = useMemo(() => {
    if (!jsonArray) return [];
    const keySet = new Set<string>();
    for (const row of jsonArray.slice(0, 100))
      for (const k of Object.keys(row)) keySet.add(k);
    return Array.from(keySet);
  }, [jsonArray]);

  // 是否有表格视图可用
  const hasTableView = !!jsonArray || !!csvData;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  function downloadBlob(data: string, fileName: string, mime: string) {
    const blob = new Blob([data], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
  }

  const baseName = artifact.name.replace(/\.[^.]+$/, '') || 'export';
  const correctExt = inferExtension(effectiveMime);
  const displayName = artifact.name.includes('.') ? artifact.name : `${artifact.name}${correctExt}`;

  function handleDownloadJson() {
    if (artifact.cosUrl) { window.open(artifact.cosUrl, '_blank'); return; }
    downloadBlob(formatJson(content), `${baseName}.json`, 'application/json');
  }

  function handleDownloadCsv() {
    if (jsonArray) {
      const csvContent = arrayToCsv(jsonArray, columns);
      downloadBlob(csvContent, `${baseName}.csv`, 'text/csv');
    } else if (artifact.cosUrl) {
      window.open(artifact.cosUrl, '_blank');
    } else {
      downloadBlob(content, `${baseName}.csv`, 'text/csv');
    }
  }

  function handleDownloadMd() {
    if (!jsonArray) return;
    const mdContent = arrayToMdTable(jsonArray, columns);
    downloadBlob(mdContent, `${baseName}.md`, 'text/markdown');
  }

  const handleOpenInNewTab = () => {
    const blob = new Blob([content], { type: 'text/html; charset=utf-8' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  };

  const handleDownloadDefault = () => {
    if (artifact.cosUrl) { window.open(artifact.cosUrl, '_blank'); return; }
    const fileName = `${baseName}${correctExt}`;
    downloadBlob(content, fileName, effectiveMime);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(8px)', WebkitBackdropFilter: 'blur(8px)' }}
      onClick={onClose}
    >
      <div
        className="relative w-[90vw] max-w-5xl max-h-[85vh] rounded-2xl flex flex-col overflow-hidden"
        style={{
          background: 'var(--glass-bg, rgba(30,30,40,0.95))',
          border: '1px solid rgba(255,255,255,0.1)',
          boxShadow: '0 25px 60px rgba(0,0,0,0.5)',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center gap-3 px-5 py-4" style={{ borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
          <FileText className="w-4 h-4 flex-shrink-0" style={{ color: 'var(--accent-gold)' }} />
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2">
              <h2 className="text-[14px] font-semibold truncate" style={{ color: 'var(--text-primary)' }}>
                {displayName}
              </h2>
              {isAutoGenerated && (
                <span
                  className="inline-flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded-full flex-shrink-0"
                  style={{ background: 'rgba(139,92,246,0.12)', color: 'rgba(139,92,246,0.85)', border: '1px solid rgba(139,92,246,0.2)' }}
                >
                  <Bot className="w-3 h-3" />
                  自动透传
                </span>
              )}
            </div>
            <p className="text-[11px] flex items-center gap-1.5" style={{ color: 'var(--text-muted)' }}>
              <span
                className="px-1.5 py-0.5 rounded text-[10px] font-medium"
                style={{ background: 'rgba(255,255,255,0.06)', color: 'var(--text-secondary)' }}
              >
                {TYPE_LABELS[detectedType]}
              </span>
              <span>{formatBytes(artifact.sizeBytes)}</span>
              {jsonArray && <span>{jsonArray.length} 条记录</span>}
              {csvData && <span>{csvData.rows.length} 行 x {csvData.columns.length} 列</span>}
              {mimeOverridden && (
                <span className="text-[9px]" style={{ color: 'rgba(245,158,11,0.7)' }}>
                  (原始: {artifact.mimeType})
                </span>
              )}
            </p>
          </div>
          <div className="flex items-center gap-1.5">
            {/* 视图切换：有表格视图或富文本时可切换 */}
            {(hasTableView || isMarkdown || isHtml) && (
              <button
                onClick={() => setViewMode(viewMode === 'preview' ? 'raw' : 'preview')}
                className="p-1.5 rounded-lg transition-colors"
                style={{
                  background: viewMode === 'preview' ? 'rgba(255,255,255,0.1)' : 'transparent',
                  color: 'var(--text-muted)',
                }}
                title={viewMode === 'preview'
                  ? (hasTableView ? '切换为源码' : '查看源码')
                  : (hasTableView ? '切换为表格' : '查看预览')
                }
              >
                {viewMode === 'preview'
                  ? <Code className="w-4 h-4" />
                  : (hasTableView ? <Table2 className="w-4 h-4" /> : <Eye className="w-4 h-4" />)
                }
              </button>
            )}
            {/* 在新标签页打开 (仅完整 HTML) */}
            {isFullHtmlPage && (
              <button
                onClick={handleOpenInNewTab}
                className="p-1.5 rounded-lg transition-colors"
                style={{ color: 'var(--text-muted)' }}
                title="在新标签页打开"
              >
                <ExternalLink className="w-4 h-4" />
              </button>
            )}
            {/* 复制 */}
            <button
              onClick={handleCopy}
              className="p-1.5 rounded-lg transition-colors"
              style={{ color: copied ? 'rgba(34,197,94,0.9)' : 'var(--text-muted)' }}
              title="复制内容"
            >
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            </button>
            {/* 下载 */}
            {jsonArray ? (
              <div className="relative">
                <button
                  onClick={() => setDownloadMenuOpen(!downloadMenuOpen)}
                  className="p-1.5 rounded-lg transition-colors flex items-center gap-0.5"
                  style={{ color: 'var(--text-muted)' }}
                  title="下载文件"
                >
                  <Download className="w-4 h-4" />
                  <ChevronDown className="w-3 h-3" />
                </button>
                {downloadMenuOpen && (
                  <>
                    <div className="fixed inset-0 z-10" onClick={() => setDownloadMenuOpen(false)} />
                    <div
                      className="absolute right-0 top-full mt-1 z-20 rounded-lg py-1 min-w-[140px]"
                      style={{
                        background: 'var(--glass-bg, rgba(30,30,40,0.98))',
                        border: '1px solid rgba(255,255,255,0.12)',
                        boxShadow: '0 8px 24px rgba(0,0,0,0.4)',
                      }}
                    >
                      {[
                        { label: 'CSV 表格', onClick: handleDownloadCsv, desc: '.csv' },
                        { label: 'Markdown 表格', onClick: handleDownloadMd, desc: '.md' },
                        { label: 'JSON 原始数据', onClick: handleDownloadJson, desc: '.json' },
                      ].map((item) => (
                        <button
                          key={item.label}
                          onClick={() => { item.onClick(); setDownloadMenuOpen(false); }}
                          className="w-full px-3 py-1.5 text-left flex items-center justify-between transition-colors hover:bg-white/5"
                        >
                          <span className="text-[12px]" style={{ color: 'var(--text-primary)' }}>{item.label}</span>
                          <span className="text-[10px]" style={{ color: 'var(--text-muted)' }}>{item.desc}</span>
                        </button>
                      ))}
                    </div>
                  </>
                )}
              </div>
            ) : (
              <button
                onClick={handleDownloadDefault}
                className="p-1.5 rounded-lg transition-colors"
                style={{ color: 'var(--text-muted)' }}
                title="下载文件"
              >
                <Download className="w-4 h-4" />
              </button>
            )}
            {/* 关闭 */}
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg transition-colors hover:bg-white/10"
              style={{ color: 'var(--text-muted)' }}
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Content - 智能渲染 */}
        <div className="flex-1 overflow-auto p-5">
          {!content && !artifact.cosUrl && (
            <div className="text-center py-12 text-[13px]" style={{ color: 'var(--text-muted)' }}>
              产物内容为空
            </div>
          )}

          {/* COS-only artifact (no inline content) */}
          {!content && artifact.cosUrl && (
            <div className="text-center py-12">
              <a
                href={artifact.cosUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg transition-colors"
                style={{ background: 'rgba(99,102,241,0.1)', color: 'rgba(99,102,241,0.9)', border: '1px solid rgba(99,102,241,0.2)' }}
              >
                <Download className="w-4 h-4" />
                下载文件
              </a>
            </div>
          )}

          {/* ══════ 预览模式 ══════ */}
          {content && viewMode === 'preview' && (
            <>
              {/* JSON 数组 → 表格 */}
              {jsonArray && (
                <DataTable
                  columns={columns}
                  rows={jsonArray.map(row => columns.map(col => formatCellValue(row[col])))}
                />
              )}

              {/* CSV → 表格 */}
              {!jsonArray && csvData && (
                <DataTable columns={csvData.columns} rows={csvData.rows} />
              )}

              {/* JSON 非数组 → 格式化 */}
              {isJson && !jsonArray && (
                <CodeBlock content={formatJson(content)} />
              )}

              {/* Markdown → 渲染 */}
              {isMarkdown && (
                <div
                  className="prose-sm text-[13px] leading-relaxed"
                  style={{ color: 'var(--text-secondary)' }}
                  dangerouslySetInnerHTML={{ __html: renderMarkdown(content) }}
                />
              )}

              {/* 完整 HTML 页面 → iframe */}
              {isHtml && isFullHtmlPage && (
                <div className="relative" style={{ height: iframeFullscreen ? '100%' : 'calc(85vh - 120px)' }}>
                  <div className="absolute top-2 right-2 z-10 flex items-center gap-1">
                    <button
                      onClick={handleOpenInNewTab}
                      className="p-1.5 rounded-lg transition-colors"
                      style={{ background: 'rgba(0,0,0,0.6)', color: 'rgba(255,255,255,0.8)' }}
                      title="在新标签页打开"
                    >
                      <ExternalLink className="w-3.5 h-3.5" />
                    </button>
                    <button
                      onClick={() => setIframeFullscreen(!iframeFullscreen)}
                      className="p-1.5 rounded-lg transition-colors"
                      style={{ background: 'rgba(0,0,0,0.6)', color: 'rgba(255,255,255,0.8)' }}
                      title={iframeFullscreen ? '退出全屏' : '全屏预览'}
                    >
                      {iframeFullscreen ? <Minimize2 className="w-3.5 h-3.5" /> : <Maximize2 className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                  <iframe
                    ref={iframeRef}
                    srcDoc={content}
                    sandbox="allow-scripts allow-same-origin"
                    className="w-full h-full rounded-xl"
                    style={{ border: '1px solid rgba(255,255,255,0.08)', background: 'transparent' }}
                    title={artifact.name}
                  />
                </div>
              )}

              {/* HTML 片段 → 内联渲染 */}
              {isHtml && !isFullHtmlPage && (
                <div
                  className="text-[13px] leading-relaxed"
                  style={{ color: 'var(--text-secondary)' }}
                  dangerouslySetInnerHTML={{ __html: content }}
                />
              )}

              {/* 图片 */}
              {isImage && (
                <div className="flex items-center justify-center">
                  <img src={content} alt={artifact.name} className="max-w-full max-h-[70vh] rounded-lg" />
                </div>
              )}

              {/* 纯文本 fallback */}
              {detectedType === 'text' && !hasTableView && (
                <CodeBlock content={content} />
              )}
            </>
          )}

          {/* ══════ 源码模式 ══════ */}
          {content && viewMode === 'raw' && (
            <CodeBlock content={isJson && !jsonArray ? formatJson(content) : content} />
          )}
        </div>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
// 子组件
// ═══════════════════════════════════════════════════════════════

/** 代码块 */
function CodeBlock({ content }: { content: string }) {
  return (
    <pre
      className="text-[12px] font-mono leading-relaxed p-4 rounded-xl overflow-auto whitespace-pre-wrap"
      style={{
        background: 'rgba(0,0,0,0.3)',
        color: 'var(--text-secondary)',
        border: '1px solid rgba(255,255,255,0.06)',
      }}
    >
      {content}
    </pre>
  );
}

/** 数据表格（JSON 数组 / CSV 共用） */
function DataTable({ columns, rows }: { columns: string[]; rows: string[][] }) {
  return (
    <div className="overflow-auto rounded-xl" style={{ border: '1px solid rgba(255,255,255,0.08)' }}>
      <table className="w-full text-[11px]" style={{ borderCollapse: 'collapse' }}>
        <thead>
          <tr style={{ background: 'rgba(255,255,255,0.06)' }}>
            <th
              className="text-left px-3 py-2 font-semibold sticky top-0"
              style={{ color: 'var(--text-muted)', background: 'rgba(30,30,40,0.98)', borderBottom: '1px solid rgba(255,255,255,0.1)', minWidth: 32 }}
            >
              #
            </th>
            {columns.map((col) => (
              <th
                key={col}
                className="text-left px-3 py-2 font-semibold sticky top-0 whitespace-nowrap"
                style={{ color: 'var(--text-muted)', background: 'rgba(30,30,40,0.98)', borderBottom: '1px solid rgba(255,255,255,0.1)' }}
              >
                {col}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, rowIdx) => (
            <tr
              key={rowIdx}
              className="transition-colors hover:bg-white/[0.02]"
              style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}
            >
              <td className="px-3 py-1.5" style={{ color: 'var(--text-muted)' }}>{rowIdx + 1}</td>
              {row.map((cell, colIdx) => (
                <td
                  key={colIdx}
                  className="px-3 py-1.5 max-w-[300px] truncate"
                  style={{ color: 'var(--text-secondary)' }}
                  title={cell}
                >
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
// 工具函数
// ═══════════════════════════════════════════════════════════════

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${(bytes / Math.pow(k, i)).toFixed(1)} ${sizes[i]}`;
}

function formatJson(s: string): string {
  try { return JSON.stringify(JSON.parse(s), null, 2); }
  catch { return s; }
}

function formatCellValue(val: unknown): string {
  if (val == null) return '';
  if (typeof val === 'object') return JSON.stringify(val);
  return String(val);
}

function inferExtension(mime: string): string {
  if (mime.includes('html')) return '.html';
  if (mime.includes('json')) return '.json';
  if (mime.includes('markdown')) return '.md';
  if (mime.includes('csv')) return '.csv';
  if (mime.includes('xml')) return '.xml';
  if (mime.includes('png')) return '.png';
  if (mime.includes('jpeg') || mime.includes('jpg')) return '.jpg';
  if (mime.includes('pdf')) return '.pdf';
  return '.txt';
}

/** 简易 CSV 行解析（支持引号内逗号） */
function parseCsvLine(line: string): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (ch === ',' && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += ch;
    }
  }
  result.push(current.trim());
  return result;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function renderMarkdown(md: string): string {
  const tableRegex = /^(\|.+\|)\n(\|[\s:|-]+\|)\n((?:\|.+\|\n?)+)/gm;
  let processed = md.replace(tableRegex, (_match, headerLine: string, _sepLine: string, bodyBlock: string) => {
    const headers = headerLine.split('|').filter((_: string, i: number, a: string[]) => i > 0 && i < a.length - 1).map((h: string) => h.trim());
    const rows = bodyBlock.trim().split('\n').map((row: string) =>
      row.split('|').filter((_: string, i: number, a: string[]) => i > 0 && i < a.length - 1).map((c: string) => c.trim())
    );
    const thStyle = 'padding:6px 10px;text-align:left;border-bottom:2px solid rgba(255,255,255,0.15);font-size:12px;font-weight:600;color:var(--text-primary)';
    const tdStyle = 'padding:5px 10px;border-bottom:1px solid rgba(255,255,255,0.06);font-size:12px;color:var(--text-secondary)';
    const ths = headers.map((h: string) => `<th style="${thStyle}">${h}</th>`).join('');
    const trs = rows.map((cols: string[]) => `<tr>${cols.map((c: string) => `<td style="${tdStyle}">${c}</td>`).join('')}</tr>`).join('');
    return `<table style="width:100%;border-collapse:collapse;margin:12px 0;border:1px solid rgba(255,255,255,0.08);border-radius:6px;overflow:hidden"><thead><tr>${ths}</tr></thead><tbody>${trs}</tbody></table>`;
  });

  const html = processed
    .replace(/```[\s\S]*?```/g, (m) => {
      const code = m.replace(/```\w*\n?/, '').replace(/\n?```$/, '');
      return `<pre style="background:rgba(0,0,0,0.3);padding:12px;border-radius:8px;overflow-x:auto;font-size:12px;line-height:1.5;border:1px solid rgba(255,255,255,0.08)"><code>${escapeHtml(code)}</code></pre>`;
    })
    .replace(/`([^`]+)`/g, '<code style="background:rgba(255,255,255,0.08);padding:2px 6px;border-radius:4px;font-size:12px">$1</code>')
    .replace(/^#### (.+)$/gm, '<h4 style="font-size:14px;font-weight:600;margin:16px 0 8px;color:var(--text-primary)">$1</h4>')
    .replace(/^### (.+)$/gm, '<h3 style="font-size:15px;font-weight:600;margin:20px 0 8px;color:var(--text-primary)">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="font-size:16px;font-weight:700;margin:24px 0 10px;color:var(--text-primary)">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="font-size:18px;font-weight:700;margin:24px 0 12px;color:var(--text-primary)">$1</h1>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li style="margin-left:16px;list-style:disc;margin-bottom:4px">$1</li>')
    .replace(/^\d+\. (.+)$/gm, '<li style="margin-left:16px;list-style:decimal;margin-bottom:4px">$1</li>')
    .replace(/^---+$/gm, '<hr style="border:none;border-top:1px solid rgba(255,255,255,0.1);margin:16px 0">')
    .replace(/\n\n/g, '</p><p style="margin:8px 0;line-height:1.7">')
    .replace(/\n/g, '<br>');
  return `<p style="margin:8px 0;line-height:1.7">${html}</p>`;
}

/** JSON array → CSV string */
function arrayToCsv(arr: Record<string, unknown>[], columns: string[]): string {
  const escapeCsv = (val: unknown): string => {
    const s = val == null ? '' : typeof val === 'object' ? JSON.stringify(val) : String(val);
    if (s.includes(',') || s.includes('"') || s.includes('\n'))
      return `"${s.replace(/"/g, '""')}"`;
    return s;
  };
  const header = columns.map(escapeCsv).join(',');
  const rows = arr.map(row => columns.map(col => escapeCsv(row[col])).join(','));
  return [header, ...rows].join('\n');
}

/** JSON array → Markdown table */
function arrayToMdTable(arr: Record<string, unknown>[], columns: string[]): string {
  const escapeMd = (val: unknown): string => {
    const s = val == null ? '' : typeof val === 'object' ? JSON.stringify(val) : String(val);
    return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
  };
  const header = `| ${columns.join(' | ')} |`;
  const separator = `| ${columns.map(() => '---').join(' | ')} |`;
  const rows = arr.map(row => `| ${columns.map(col => escapeMd(row[col])).join(' | ')} |`);
  return [header, separator, ...rows].join('\n');
}
