import type { ApiResponse } from '@/types/api';

// ========== Data Models ==========

export interface ReportTeam {
  id: string;
  name: string;
  parentTeamId?: string;
  leaderUserId: string;
  leaderName?: string;
  description?: string;
  /** v2.0 绑定的采集工作流 ID */
  dataCollectionWorkflowId?: string;
  /** v2.0 使用的预置工作流模板 key */
  workflowTemplateKey?: string;
  /** 周报可见性: all_members / leaders_only */
  reportVisibility?: string;
  /** 每周自动提交时间 (如 "friday-18:00")，null 不自动提交 */
  autoSubmitSchedule?: string;
  /** 团队自定义每日打点标签 */
  customDailyLogTags?: string[];
  /** 当前用户在该团队的角色: leader / deputy / member */
  myRole?: string | null;
  /** 当前用户与团队关系: managed / joined */
  relationType?: 'managed' | 'joined' | null;
  /** 当前用户是否可管理成员 */
  canManageMembers?: boolean;
  /** 当前用户是否可主动退出该团队 */
  canLeave?: boolean;
  createdAt: string;
  updatedAt: string;
}

export const ReportVisibilityMode = {
  AllMembers: 'all_members',
  LeadersOnly: 'leaders_only',
} as const;

export interface ReportTeamMember {
  id: string;
  teamId: string;
  userId: string;
  userName?: string;
  avatarFileName?: string;
  role: string;
  jobTitle?: string;
  /** v2.0 多平台身份映射 { github: "zhangsan", tapd: "zhangsan@company.com" } */
  identityMappings?: Record<string, string>;
  joinedAt: string;
}

export interface ReportTemplate {
  id: string;
  name: string;
  description?: string;
  sections: ReportTemplateSection[];
  teamId?: string;
  jobTitle?: string;
  isDefault: boolean;
  /** v2.0 系统预置模板不可删除 */
  isSystem?: boolean;
  /** v2.0 模板唯一标识 key */
  templateKey?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface ReportTemplateSection {
  title: string;
  description?: string;
  inputType: string;
  isRequired: boolean;
  sortOrder: number;
  dataSourceHint?: string;
  maxItems?: number;
  /** v2.0 板块类型: auto-stats / auto-list / manual-list / free-text */
  sectionType?: string;
  /** v2.0 关联的数据源类型 */
  dataSources?: string[];
}

export interface WeeklyReport {
  id: string;
  userId: string;
  userName?: string;
  avatarFileName?: string;
  teamId: string;
  teamName?: string;
  templateId: string;
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  status: string;
  sections: WeeklyReportSection[];
  submittedAt?: string;
  reviewedAt?: string;
  reviewedBy?: string;
  reviewedByName?: string;
  returnReason?: string;
  returnedBy?: string;
  returnedByName?: string;
  returnedAt?: string;
  autoGeneratedAt?: string;
  /** v2.0 关联的采集工作流执行 ID */
  workflowExecutionId?: string;
  /** v2.0 提交时快照的统计数据 */
  statsSnapshot?: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface WeeklyReportSection {
  templateSection: ReportTemplateSection;
  items: WeeklyReportItem[];
}

export interface WeeklyReportItem {
  content: string;
  source: string;
  sourceRef?: string;
}

export interface ReportUser {
  id: string;
  username: string;
  displayName?: string;
  avatarFileName?: string;
}

export interface TeamDashboardMember {
  userId: string;
  userName?: string;
  avatarFileName?: string;
  role: string;
  jobTitle?: string;
  reportId?: string;
  reportStatus: string;
  submittedAt?: string;
}

export interface TeamDashboardStats {
  total: number;
  submitted: number;
  reviewed: number;
  draft: number;
  notStarted: number;
}

export interface TeamDashboardData {
  team: ReportTeam;
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  members: TeamDashboardMember[];
  stats: TeamDashboardStats;
}

// ========== Phase 2: Daily Logs ==========

export interface DailyLog {
  id: string;
  userId: string;
  userName?: string;
  date: string;
  items: DailyLogItem[];
  createdAt: string;
  updatedAt: string;
}

export interface DailyLogItem {
  content: string;
  category: string;
  /** 自定义标签列表 */
  tags?: string[];
  durationMinutes?: number;
  createdAt?: string;
}

export const DailyLogCategory = {
  Development: 'development',
  Meeting: 'meeting',
  Communication: 'communication',
  Documentation: 'documentation',
  Testing: 'testing',
  Other: 'other',
} as const;

export const DailyLogCategoryLabels: Record<string, string> = {
  development: '开发',
  meeting: '会议',
  communication: '沟通',
  documentation: '文档',
  testing: '测试',
  other: '其他',
};

// ========== Phase 2: Data Sources ==========

export interface ReportDataSource {
  id: string;
  teamId: string;
  sourceType: string;
  name: string;
  repoUrl: string;
  accessTokenMasked?: string;
  branchFilter?: string;
  userMapping: Record<string, string>;
  pollIntervalMinutes: number;
  enabled: boolean;
  lastSyncAt?: string;
  lastSyncError?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface ReportCommit {
  id: string;
  dataSourceId: string;
  mappedUserId?: string;
  authorName: string;
  authorEmail: string;
  commitHash: string;
  message: string;
  committedAt: string;
  branch?: string;
  additions: number;
  deletions: number;
  filesChanged: number;
}

// ========== Phase 2: Collected Activity ==========

export interface DefectStats {
  submitted: number;
  resolved: number;
  reopened: number;
  avgResolutionHours: number;
}

export interface CollectedActivity {
  userId: string;
  periodStart: string;
  periodEnd: string;
  // 原有数据流
  prdSessions: number;
  defectsSubmitted: number;
  visualSessions: number;
  llmCalls: number;
  dailyLogs: DailyLog[];
  commits: ReportCommit[];
  // Phase 0 新增数据流
  prdMessageCount: number;
  imageGenCompletedCount: number;
  videoGenCompletedCount: number;
  documentEditCount: number;
  workflowExecutionCount: number;
  toolboxRunCount: number;
  webPagePublishCount: number;
  attachmentUploadCount: number;
  defectDetails?: DefectStats;
}

// ========== Constants ==========

export const WeeklyReportStatus = {
  NotStarted: 'not-started',
  Draft: 'draft',
  Submitted: 'submitted',
  Reviewed: 'reviewed',
  Returned: 'returned',
  Overdue: 'overdue',
  Vacation: 'vacation',
  Viewed: 'viewed',
} as const;

/** v2.0 简化状态流: Draft → Submitted → Viewed */
export const WeeklyReportStatusV2 = [
  WeeklyReportStatus.Draft,
  WeeklyReportStatus.Submitted,
  WeeklyReportStatus.Viewed,
] as const;

export const ReportTeamRole = {
  Member: 'member',
  Leader: 'leader',
  Deputy: 'deputy',
} as const;

export const ReportInputType = {
  BulletList: 'bullet-list',
  RichText: 'rich-text',
  KeyValue: 'key-value',
  ProgressTable: 'progress-table',
} as const;

/** v2.0 板块类型 */
export const ReportSectionType = {
  AutoStats: 'auto-stats',
  AutoList: 'auto-list',
  ManualList: 'manual-list',
  FreeText: 'free-text',
} as const;

export const WeeklyReportCreationMode = {
  Manual: 'manual',
  AiDraft: 'ai-draft',
} as const;

// ========== Contract Types ==========

// --- Teams ---
export type ListReportTeamsContract = () => Promise<ApiResponse<{ items: ReportTeam[] }>>;

export type GetReportTeamContract = (input: { id: string }) => Promise<
  ApiResponse<{ team: ReportTeam; members: ReportTeamMember[] }>
>;

export type CreateReportTeamContract = (input: {
  name: string;
  leaderUserId: string;
  parentTeamId?: string;
  description?: string;
  reportVisibility?: string;
  autoSubmitSchedule?: string;
  customDailyLogTags?: string[];
}) => Promise<ApiResponse<{ team: ReportTeam }>>;

export type UpdateReportTeamContract = (input: {
  id: string;
  name?: string;
  leaderUserId?: string;
  description?: string;
  reportVisibility?: string;
  autoSubmitSchedule?: string;
  customDailyLogTags?: string[];
}) => Promise<ApiResponse<{ team: ReportTeam }>>;

export type DeleteReportTeamContract = (input: { id: string }) => Promise<ApiResponse<object>>;

export type LeaveReportTeamContract = (input: { teamId: string }) => Promise<
  ApiResponse<{ left: boolean }>
>;

// --- Team Members ---
export type AddReportTeamMemberContract = (input: {
  teamId: string;
  userId: string;
  role?: string;
  jobTitle?: string;
}) => Promise<ApiResponse<{ member: ReportTeamMember }>>;

export type RemoveReportTeamMemberContract = (input: {
  teamId: string;
  userId: string;
}) => Promise<ApiResponse<object>>;

export type UpdateReportTeamMemberContract = (input: {
  teamId: string;
  userId: string;
  role?: string;
  jobTitle?: string;
}) => Promise<ApiResponse<{ member: ReportTeamMember }>>;

// --- Users ---
export type ListReportUsersContract = () => Promise<ApiResponse<{ items: ReportUser[] }>>;

// --- Templates ---
export type ListReportTemplatesContract = () => Promise<ApiResponse<{ items: ReportTemplate[] }>>;

export type GetReportTemplateContract = (input: { id: string }) => Promise<
  ApiResponse<{ template: ReportTemplate }>
>;

export type CreateReportTemplateContract = (input: {
  name: string;
  description?: string;
  sections: Partial<ReportTemplateSection>[];
  teamId?: string;
  jobTitle?: string;
  isDefault?: boolean;
}) => Promise<ApiResponse<{ template: ReportTemplate }>>;

export type UpdateReportTemplateContract = (input: {
  id: string;
  name?: string;
  description?: string;
  sections?: Partial<ReportTemplateSection>[];
  teamId?: string;
  jobTitle?: string;
  isDefault?: boolean;
}) => Promise<ApiResponse<{ template: ReportTemplate }>>;

export type DeleteReportTemplateContract = (input: { id: string }) => Promise<ApiResponse<object>>;

// --- Reports ---
export type ListWeeklyReportsContract = (input?: {
  scope?: 'my' | 'team';
  teamId?: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<{ items: WeeklyReport[] }>>;

export type GetWeeklyReportContract = (input: { id: string }) => Promise<
  ApiResponse<{ report: WeeklyReport }>
>;

export type CreateWeeklyReportContract = (input: {
  teamId: string;
  templateId: string;
  weekYear?: number;
  weekNumber?: number;
  creationMode?: (typeof WeeklyReportCreationMode)[keyof typeof WeeklyReportCreationMode];
}) => Promise<ApiResponse<{ report: WeeklyReport }>>;

export type UpdateWeeklyReportContract = (input: {
  id: string;
  sections: { items: { content: string; source?: string; sourceRef?: string }[] }[];
}) => Promise<ApiResponse<{ report: WeeklyReport }>>;

export interface ReportRichTextImageUploadData {
  attachmentId: string;
  url: string;
  fileName: string;
  mimeType: string;
  size: number;
}

export type UploadReportRichTextImageContract = (input: {
  id: string;
  file: File;
}) => Promise<ApiResponse<ReportRichTextImageUploadData>>;

export type DeleteWeeklyReportContract = (input: { id: string }) => Promise<ApiResponse<object>>;

export type SubmitWeeklyReportContract = (input: { id: string }) => Promise<
  ApiResponse<{ report: WeeklyReport }>
>;

export type ReviewWeeklyReportContract = (input: { id: string }) => Promise<
  ApiResponse<{ report: WeeklyReport }>
>;

export type ReturnWeeklyReportContract = (input: {
  id: string;
  reason: string;
}) => Promise<ApiResponse<{ report: WeeklyReport }>>;

// --- Dashboard ---
export type GetTeamDashboardContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<TeamDashboardData>>;

// --- Daily Logs ---
export type SaveDailyLogContract = (input: {
  date: string;
  items: { content: string; category: string; tags?: string[]; durationMinutes?: number; createdAt?: string }[];
}) => Promise<ApiResponse<DailyLog>>;

export type ListDailyLogsContract = (input?: {
  startDate?: string;
  endDate?: string;
}) => Promise<ApiResponse<{ items: DailyLog[] }>>;

export type GetDailyLogContract = (input: { date: string }) => Promise<ApiResponse<DailyLog>>;

export type DeleteDailyLogContract = (input: { date: string }) => Promise<ApiResponse<{ deleted: boolean }>>;

// --- Data Sources ---
export type ListDataSourcesContract = (input?: {
  teamId?: string;
}) => Promise<ApiResponse<{ items: ReportDataSource[] }>>;

export type CreateDataSourceContract = (input: {
  teamId: string;
  sourceType?: string;
  name: string;
  repoUrl: string;
  accessToken?: string;
  branchFilter?: string;
  userMapping?: Record<string, string>;
  pollIntervalMinutes?: number;
}) => Promise<ApiResponse<{ id: string }>>;

export type UpdateDataSourceContract = (input: {
  id: string;
  name?: string;
  repoUrl?: string;
  accessToken?: string;
  branchFilter?: string;
  userMapping?: Record<string, string>;
  pollIntervalMinutes?: number;
  enabled?: boolean;
}) => Promise<ApiResponse<object>>;

export type DeleteDataSourceContract = (input: { id: string }) => Promise<ApiResponse<object>>;

export type TestDataSourceContract = (input: {
  id: string;
}) => Promise<ApiResponse<{ success: boolean; error?: string }>>;

export type SyncDataSourceContract = (input: {
  id: string;
}) => Promise<ApiResponse<{ syncedCommits: number; error?: string }>>;

export type ListDataSourceCommitsContract = (input: {
  id: string;
  since?: string;
  until?: string;
  limit?: number;
}) => Promise<ApiResponse<{ items: ReportCommit[] }>>;

// --- AI Generation ---
export type GenerateReportContract = (input: {
  id: string;
}) => Promise<ApiResponse<WeeklyReport>>;

export type GetCollectedActivityContract = (input?: {
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<CollectedActivity>>;

// ========== Phase 3: Comments ==========

export interface ReportComment {
  id: string;
  reportId: string;
  sectionIndex: number;
  sectionTitleSnapshot: string;
  parentCommentId?: string;
  authorUserId: string;
  authorDisplayName: string;
  content: string;
  createdAt: string;
  updatedAt?: string;
}

export interface ReportLikeUser {
  userId: string;
  userName: string;
  avatarFileName?: string;
  likedAt: string;
}

export interface ReportLikeSummary {
  likedByMe: boolean;
  count: number;
  users: ReportLikeUser[];
}

export type ListCommentsContract = (input: {
  reportId: string;
  sectionIndex?: number;
}) => Promise<ApiResponse<{ items: ReportComment[] }>>;

export type CreateCommentContract = (input: {
  reportId: string;
  sectionIndex: number;
  content: string;
  parentCommentId?: string;
}) => Promise<ApiResponse<{ comment: ReportComment }>>;

export type DeleteCommentContract = (input: {
  reportId: string;
  commentId: string;
}) => Promise<ApiResponse<object>>;

export type ListReportLikesContract = (input: {
  reportId: string;
}) => Promise<ApiResponse<ReportLikeSummary>>;

export type LikeReportContract = (input: {
  reportId: string;
}) => Promise<ApiResponse<ReportLikeSummary>>;

export type UnlikeReportContract = (input: {
  reportId: string;
}) => Promise<ApiResponse<ReportLikeSummary>>;

// ========== Phase 3: Plan Comparison ==========

export interface PlanComparison {
  lastWeekPlans: string[];
  thisWeekActuals: string[];
  lastWeekLabel?: string;
  thisWeekLabel: string;
  hasLastWeek: boolean;
}

export type GetPlanComparisonContract = (input: {
  reportId: string;
}) => Promise<ApiResponse<PlanComparison>>;

// ========== Phase 3: Team Summary ==========

export interface TeamSummary {
  id: string;
  teamId: string;
  teamName: string;
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  sections: TeamSummarySection[];
  sourceReportIds: string[];
  memberCount: number;
  submittedCount: number;
  generatedBy?: string;
  generatedByName?: string;
  generatedAt: string;
  updatedAt: string;
}

export interface TeamSummarySection {
  title: string;
  items: string[];
}

export type TeamSummaryVisibilityScope = 'full_team' | 'self_only' | 'none';
export type TeamSummaryKind = 'team_summary' | 'self_report' | 'none';

export interface TeamSummaryViewData {
  team: ReportTeam;
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  visibilityScope: TeamSummaryVisibilityScope;
  summaryKind: TeamSummaryKind;
  summary: TeamSummary | null;
  message?: string;
  canGenerateSummary: boolean;
  canManageMembers: boolean;
  canViewAllMembers: boolean;
  members: TeamDashboardMember[];
}

export interface TeamReportsViewStats {
  totalMembers: number;
  submittedCount: number;
  pendingCount: number;
}

export interface TeamReportListItem {
  reportId: string;
  userId: string;
  userName?: string;
  avatarFileName?: string;
  status: string;
  submittedAt?: string;
  updatedAt: string;
  teamId: string;
  teamName?: string;
  weekYear: number;
  weekNumber: number;
}

export interface TeamReportsViewData {
  team: ReportTeam;
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  visibilityScope: TeamSummaryVisibilityScope;
  stats: TeamReportsViewStats;
  items: TeamReportListItem[];
  members: TeamDashboardMember[];
  message?: string;
  canGenerateSummary: boolean;
  canManageMembers: boolean;
  canViewAllMembers: boolean;
}

export type GenerateTeamSummaryContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<{ summary: TeamSummary }>>;

export type GetTeamSummaryContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<{ summary: TeamSummary | null }>>;

export type GetTeamSummaryViewContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<TeamSummaryViewData>>;

export type GetTeamReportsViewContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<TeamReportsViewData>>;

// ========== Phase 4: History Trends ==========

export interface PersonalTrendItem {
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  reportStatus: string;
  sectionCount: number;
  commitCount: number;
  dailyLogDays: number;
  submittedAt?: string;
}

export interface TeamTrendItem {
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  memberCount: number;
  submittedCount: number;
  reviewedCount: number;
  overdueCount: number;
  submissionRate: number;
  commitCount: number;
}

export type GetPersonalTrendsContract = (input?: {
  weeks?: number;
}) => Promise<ApiResponse<{ items: PersonalTrendItem[]; weeks: number }>>;

export type GetTeamTrendsContract = (input: {
  teamId: string;
  weeks?: number;
}) => Promise<ApiResponse<{ items: TeamTrendItem[]; weeks: number; teamId: string }>>;

// ========== Phase 4: Export ==========

export type ExportReportMarkdownContract = (input: {
  id: string;
}) => Promise<Blob>;

export type ExportTeamSummaryMarkdownContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<Blob>;

// ========== Phase 4: Vacation ==========

export type MarkVacationContract = (input: {
  teamId: string;
  userId: string;
  weekYear?: number;
  weekNumber?: number;
  reason?: string;
}) => Promise<ApiResponse<{ report: WeeklyReport }>>;

export type CancelVacationContract = (input: {
  teamId: string;
  userId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<{ deleted: boolean }>>;

// ========== Phase 5/6: v2.0 Contracts ==========

// --- AI Sources ---
export interface ReportAiSource {
  key: string;
  name: string;
  description: string;
  enabled: boolean;
  locked: boolean;
}

export type ListMyAiSourcesContract = () => Promise<ApiResponse<{ items: ReportAiSource[] }>>;

export type UpdateMyAiSourceContract = (input: {
  key: string;
  enabled: boolean;
}) => Promise<ApiResponse<{ source: { key: string; enabled: boolean } }>>;

export type GetMyDailyLogTagsContract = () => Promise<ApiResponse<{ items: string[] }>>;

export type UpdateMyDailyLogTagsContract = (input: {
  items: string[];
}) => Promise<ApiResponse<{ items: string[] }>>;

// --- Personal Sources ---
export interface PersonalSource {
  id: string;
  userId: string;
  sourceType: string;
  displayName: string;
  config: PersonalSourceConfig;
  enabled: boolean;
  lastSyncAt?: string;
  lastSyncStatus: string;
  lastSyncError?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PersonalSourceConfig {
  repoUrl?: string;
  username?: string;
  spaceId?: string;
}

export type ListPersonalSourcesContract = () => Promise<ApiResponse<{ items: PersonalSource[] }>>;

export type CreatePersonalSourceContract = (input: {
  sourceType: string;
  displayName: string;
  repoUrl?: string;
  username?: string;
  spaceId?: string;
  apiEndpoint?: string;
  token: string;
}) => Promise<ApiResponse<{ source: PersonalSource }>>;

export type UpdatePersonalSourceContract = (input: {
  id: string;
  displayName?: string;
  repoUrl?: string;
  username?: string;
  spaceId?: string;
  apiEndpoint?: string;
  token?: string;
  enabled?: boolean;
}) => Promise<ApiResponse<{ source: PersonalSource }>>;

export type DeletePersonalSourceContract = (input: { id: string }) => Promise<ApiResponse<object>>;

export type TestPersonalSourceContract = (input: { id: string }) => Promise<ApiResponse<{ success: boolean }>>;

export type SyncPersonalSourceContract = (input: { id: string }) => Promise<ApiResponse<{ success: boolean }>>;

export interface PersonalStats {
  sources: PersonalSourceStats[];
}

export interface PersonalSourceStats {
  sourceType: string;
  displayName: string;
  summary: Record<string, number>;
  details: PersonalStatsDetail[];
}

export interface PersonalStatsDetail {
  title: string;
  type: string;
  date?: string;
}

export type GetPersonalStatsContract = (input?: {
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<PersonalStats>>;

// --- Team Workflow ---
export interface TeamWorkflowInfo {
  workflowId?: string;
  workflowName?: string;
  templateKey?: string;
  lastExecution?: {
    id: string;
    status: string;
    startedAt: string;
    completedAt?: string;
    durationMs?: number;
  };
}

export type GetTeamWorkflowContract = (input: {
  teamId: string;
}) => Promise<ApiResponse<TeamWorkflowInfo>>;

export type RunTeamWorkflowContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<{ executionId: string }>>;

// --- Identity Mappings ---
export type UpdateIdentityMappingsContract = (input: {
  teamId: string;
  userId: string;
  identityMappings: Record<string, string>;
}) => Promise<ApiResponse<{ member: ReportTeamMember }>>;

// --- Seed Templates ---
export type SeedSystemTemplatesContract = () => Promise<ApiResponse<{ inserted: string[]; skipped: number }>>;
