import type { ApiResponse } from '@/types/api';

// ========== Data Models ==========

export interface ReportTeam {
  id: string;
  name: string;
  parentTeamId?: string;
  leaderUserId: string;
  leaderName?: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ReportTeamMember {
  id: string;
  teamId: string;
  userId: string;
  userName?: string;
  avatarFileName?: string;
  role: string;
  jobTitle?: string;
  joinedAt: string;
}

export interface ReportTemplate {
  id: string;
  name: string;
  description?: string;
  sections: ReportTemplateSection[];
  teamId?: string;
  jobTitle?: string;
  isDefault: boolean;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface ReportTemplateSection {
  title: string;
  description?: string;
  inputType: string;
  isRequired: boolean;
  sortOrder: number;
  dataSourceHint?: string;
  maxItems?: number;
}

export interface WeeklyReport {
  id: string;
  userId: string;
  userName?: string;
  avatarFileName?: string;
  teamId: string;
  teamName?: string;
  templateId: string;
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  status: string;
  sections: WeeklyReportSection[];
  submittedAt?: string;
  reviewedAt?: string;
  reviewedBy?: string;
  reviewedByName?: string;
  returnReason?: string;
  returnedBy?: string;
  returnedByName?: string;
  returnedAt?: string;
  autoGeneratedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface WeeklyReportSection {
  templateSection: ReportTemplateSection;
  items: WeeklyReportItem[];
}

export interface WeeklyReportItem {
  content: string;
  source: string;
  sourceRef?: string;
}

export interface ReportUser {
  id: string;
  username: string;
  displayName?: string;
  avatarFileName?: string;
}

export interface TeamDashboardMember {
  userId: string;
  userName?: string;
  avatarFileName?: string;
  role: string;
  jobTitle?: string;
  reportId?: string;
  reportStatus: string;
  submittedAt?: string;
}

export interface TeamDashboardStats {
  total: number;
  submitted: number;
  reviewed: number;
  draft: number;
  notStarted: number;
}

export interface TeamDashboardData {
  team: ReportTeam;
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  members: TeamDashboardMember[];
  stats: TeamDashboardStats;
}

// ========== Phase 2: Daily Logs ==========

export interface DailyLog {
  id: string;
  userId: string;
  userName?: string;
  date: string;
  items: DailyLogItem[];
  createdAt: string;
  updatedAt: string;
}

export interface DailyLogItem {
  content: string;
  category: string;
  durationMinutes?: number;
}

export const DailyLogCategory = {
  Development: 'development',
  Meeting: 'meeting',
  Communication: 'communication',
  Documentation: 'documentation',
  Testing: 'testing',
  Other: 'other',
} as const;

export const DailyLogCategoryLabels: Record<string, string> = {
  development: '开发',
  meeting: '会议',
  communication: '沟通',
  documentation: '文档',
  testing: '测试',
  other: '其他',
};

// ========== Phase 2: Data Sources ==========

export interface ReportDataSource {
  id: string;
  teamId: string;
  sourceType: string;
  name: string;
  repoUrl: string;
  accessTokenMasked?: string;
  branchFilter?: string;
  userMapping: Record<string, string>;
  pollIntervalMinutes: number;
  enabled: boolean;
  lastSyncAt?: string;
  lastSyncError?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface ReportCommit {
  id: string;
  dataSourceId: string;
  mappedUserId?: string;
  authorName: string;
  authorEmail: string;
  commitHash: string;
  message: string;
  committedAt: string;
  branch?: string;
  additions: number;
  deletions: number;
  filesChanged: number;
}

// ========== Phase 2: Collected Activity ==========

export interface CollectedActivity {
  userId: string;
  periodStart: string;
  periodEnd: string;
  prdSessions: number;
  defectsSubmitted: number;
  visualSessions: number;
  llmCalls: number;
  dailyLogs: DailyLog[];
  commits: ReportCommit[];
}

// ========== Constants ==========

export const WeeklyReportStatus = {
  NotStarted: 'not-started',
  Draft: 'draft',
  Submitted: 'submitted',
  Reviewed: 'reviewed',
  Returned: 'returned',
  Overdue: 'overdue',
} as const;

export const ReportTeamRole = {
  Member: 'member',
  Leader: 'leader',
  Deputy: 'deputy',
} as const;

export const ReportInputType = {
  BulletList: 'bullet-list',
  RichText: 'rich-text',
  KeyValue: 'key-value',
  ProgressTable: 'progress-table',
} as const;

// ========== Contract Types ==========

// --- Teams ---
export type ListReportTeamsContract = () => Promise<ApiResponse<{ items: ReportTeam[] }>>;

export type GetReportTeamContract = (input: { id: string }) => Promise<
  ApiResponse<{ team: ReportTeam; members: ReportTeamMember[] }>
>;

export type CreateReportTeamContract = (input: {
  name: string;
  leaderUserId: string;
  parentTeamId?: string;
  description?: string;
}) => Promise<ApiResponse<{ team: ReportTeam }>>;

export type UpdateReportTeamContract = (input: {
  id: string;
  name?: string;
  leaderUserId?: string;
  description?: string;
}) => Promise<ApiResponse<{ team: ReportTeam }>>;

export type DeleteReportTeamContract = (input: { id: string }) => Promise<ApiResponse<object>>;

// --- Team Members ---
export type AddReportTeamMemberContract = (input: {
  teamId: string;
  userId: string;
  role?: string;
  jobTitle?: string;
}) => Promise<ApiResponse<{ member: ReportTeamMember }>>;

export type RemoveReportTeamMemberContract = (input: {
  teamId: string;
  userId: string;
}) => Promise<ApiResponse<object>>;

export type UpdateReportTeamMemberContract = (input: {
  teamId: string;
  userId: string;
  role?: string;
  jobTitle?: string;
}) => Promise<ApiResponse<{ member: ReportTeamMember }>>;

// --- Users ---
export type ListReportUsersContract = () => Promise<ApiResponse<{ items: ReportUser[] }>>;

// --- Templates ---
export type ListReportTemplatesContract = () => Promise<ApiResponse<{ items: ReportTemplate[] }>>;

export type GetReportTemplateContract = (input: { id: string }) => Promise<
  ApiResponse<{ template: ReportTemplate }>
>;

export type CreateReportTemplateContract = (input: {
  name: string;
  description?: string;
  sections: Partial<ReportTemplateSection>[];
  teamId?: string;
  jobTitle?: string;
  isDefault?: boolean;
}) => Promise<ApiResponse<{ template: ReportTemplate }>>;

export type UpdateReportTemplateContract = (input: {
  id: string;
  name?: string;
  description?: string;
  sections?: Partial<ReportTemplateSection>[];
  teamId?: string;
  jobTitle?: string;
  isDefault?: boolean;
}) => Promise<ApiResponse<{ template: ReportTemplate }>>;

export type DeleteReportTemplateContract = (input: { id: string }) => Promise<ApiResponse<object>>;

// --- Reports ---
export type ListWeeklyReportsContract = (input?: {
  scope?: 'my' | 'team';
  teamId?: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<{ items: WeeklyReport[] }>>;

export type GetWeeklyReportContract = (input: { id: string }) => Promise<
  ApiResponse<{ report: WeeklyReport }>
>;

export type CreateWeeklyReportContract = (input: {
  teamId: string;
  templateId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<{ report: WeeklyReport }>>;

export type UpdateWeeklyReportContract = (input: {
  id: string;
  sections: { items: { content: string; source?: string; sourceRef?: string }[] }[];
}) => Promise<ApiResponse<{ report: WeeklyReport }>>;

export type DeleteWeeklyReportContract = (input: { id: string }) => Promise<ApiResponse<object>>;

export type SubmitWeeklyReportContract = (input: { id: string }) => Promise<
  ApiResponse<{ report: WeeklyReport }>
>;

export type ReviewWeeklyReportContract = (input: { id: string }) => Promise<
  ApiResponse<{ report: WeeklyReport }>
>;

export type ReturnWeeklyReportContract = (input: {
  id: string;
  reason?: string;
}) => Promise<ApiResponse<{ report: WeeklyReport }>>;

// --- Dashboard ---
export type GetTeamDashboardContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<TeamDashboardData>>;

// --- Daily Logs ---
export type SaveDailyLogContract = (input: {
  date: string;
  items: { content: string; category: string; durationMinutes?: number }[];
}) => Promise<ApiResponse<DailyLog>>;

export type ListDailyLogsContract = (input?: {
  startDate?: string;
  endDate?: string;
}) => Promise<ApiResponse<{ items: DailyLog[] }>>;

export type GetDailyLogContract = (input: { date: string }) => Promise<ApiResponse<DailyLog>>;

export type DeleteDailyLogContract = (input: { date: string }) => Promise<ApiResponse<{ deleted: boolean }>>;

// --- Data Sources ---
export type ListDataSourcesContract = (input?: {
  teamId?: string;
}) => Promise<ApiResponse<{ items: ReportDataSource[] }>>;

export type CreateDataSourceContract = (input: {
  teamId: string;
  name: string;
  repoUrl: string;
  accessToken?: string;
  branchFilter?: string;
  userMapping?: Record<string, string>;
  pollIntervalMinutes?: number;
}) => Promise<ApiResponse<{ id: string }>>;

export type UpdateDataSourceContract = (input: {
  id: string;
  name?: string;
  repoUrl?: string;
  accessToken?: string;
  branchFilter?: string;
  userMapping?: Record<string, string>;
  pollIntervalMinutes?: number;
  enabled?: boolean;
}) => Promise<ApiResponse<object>>;

export type DeleteDataSourceContract = (input: { id: string }) => Promise<ApiResponse<object>>;

export type TestDataSourceContract = (input: {
  id: string;
}) => Promise<ApiResponse<{ success: boolean; error?: string }>>;

export type SyncDataSourceContract = (input: {
  id: string;
}) => Promise<ApiResponse<{ syncedCommits: number; error?: string }>>;

export type ListDataSourceCommitsContract = (input: {
  id: string;
  since?: string;
  until?: string;
  limit?: number;
}) => Promise<ApiResponse<{ items: ReportCommit[] }>>;

// --- AI Generation ---
export type GenerateReportContract = (input: {
  id: string;
}) => Promise<ApiResponse<WeeklyReport>>;

export type GetCollectedActivityContract = (input?: {
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<CollectedActivity>>;

// ========== Phase 3: Comments ==========

export interface ReportComment {
  id: string;
  reportId: string;
  sectionIndex: number;
  sectionTitleSnapshot: string;
  parentCommentId?: string;
  authorUserId: string;
  authorDisplayName: string;
  content: string;
  createdAt: string;
  updatedAt?: string;
}

export type ListCommentsContract = (input: {
  reportId: string;
  sectionIndex?: number;
}) => Promise<ApiResponse<{ items: ReportComment[] }>>;

export type CreateCommentContract = (input: {
  reportId: string;
  sectionIndex: number;
  content: string;
  parentCommentId?: string;
}) => Promise<ApiResponse<{ comment: ReportComment }>>;

export type DeleteCommentContract = (input: {
  reportId: string;
  commentId: string;
}) => Promise<ApiResponse<object>>;

// ========== Phase 3: Plan Comparison ==========

export interface PlanComparison {
  lastWeekPlans: string[];
  thisWeekActuals: string[];
  lastWeekLabel?: string;
  thisWeekLabel: string;
  hasLastWeek: boolean;
}

export type GetPlanComparisonContract = (input: {
  reportId: string;
}) => Promise<ApiResponse<PlanComparison>>;

// ========== Phase 3: Team Summary ==========

export interface TeamSummary {
  id: string;
  teamId: string;
  teamName: string;
  weekYear: number;
  weekNumber: number;
  periodStart: string;
  periodEnd: string;
  sections: TeamSummarySection[];
  sourceReportIds: string[];
  memberCount: number;
  submittedCount: number;
  generatedBy?: string;
  generatedByName?: string;
  generatedAt: string;
  updatedAt: string;
}

export interface TeamSummarySection {
  title: string;
  items: string[];
}

export type GenerateTeamSummaryContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<{ summary: TeamSummary }>>;

export type GetTeamSummaryContract = (input: {
  teamId: string;
  weekYear?: number;
  weekNumber?: number;
}) => Promise<ApiResponse<{ summary: TeamSummary | null }>>;
