export type FrontEndProjectKind = 'miniapp' | 'admin' | 'h5' | 'static' | 'legacy' | 'site';

export interface FrontEndProjectEntry {
  name: string;
  kind: FrontEndProjectKind;
  tech: string;
  codingUrl?: string;
  githubUrl?: string;
  svnUrl?: string;
  docUrl?: string;
  buildUrl?: string;
  localUrl?: string;
  branches?: string;
  release?: string;
  notes?: string;
  tags: string[];
}

export const FRONT_END_PROJECTS: FrontEndProjectEntry[] = [
  {
    name: '万能零售助手',
    kind: 'miniapp',
    tech: 'uniapp',
    codingUrl: 'https://miduoyanfa.coding.net/p/pingtai/d/retail-assistant-mp/git',
    githubUrl: 'https://github.com/MiDouTech/retail-assistant-mp.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    release: '支持灰度的应用线上需选择 prod 分支并设置 RELEASE_ENV=prod',
    tags: ['零售', '小程序', 'uniapp', 'retail-assistant-mp'],
  },
  {
    name: '业务帮帮',
    kind: 'miniapp',
    tech: 'uniapp（TS + JS 混合）',
    codingUrl: 'https://miduoyanfa.coding.net/p/pingtai/d/salesman-helper-mp/git',
    githubUrl: 'https://github.com/MiDouTech/salesman-helper-mp.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['业务帮帮', '小程序', 'salesman-helper-mp'],
  },
  {
    name: '新经销助手',
    kind: 'miniapp',
    tech: 'uniapp',
    codingUrl: 'https://miduoyanfa.coding.net/p/pingtai/d/distribution-assistant-mp/git',
    githubUrl: 'https://github.com/MiDouTech/distribution-assistant-mp.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['经销', '小程序', 'distribution-assistant-mp'],
  },
  {
    name: '金牌导购员',
    kind: 'miniapp',
    tech: 'uniapp',
    codingUrl: 'https://miduoyanfa.coding.net/p/pingtai/d/guide-assistant-mp/git',
    githubUrl: 'https://github.com/MiDouTech/guide-assistant-mp.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['导购', '小程序', 'guide-assistant-mp'],
  },
  {
    name: '会员小程序（重构）',
    kind: 'miniapp',
    tech: 'uniapp',
    codingUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/d/md-user-mp/git',
    githubUrl: 'https://github.com/MiDouTech/md-user-mp.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['会员', '小程序', 'md-user-mp'],
  },
  {
    name: '会员小程序管理后台（重构）',
    kind: 'admin',
    tech: 'vue + typescript',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/md-user-admin.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['会员', '后台', 'md-user-admin'],
  },
  {
    name: '积分商城管理后台',
    kind: 'admin',
    tech: 'vue + typescript',
    codingUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/d/integral-mall/git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['积分商城', '后台', 'integral-mall'],
  },
  {
    name: '企业微信管理后台',
    kind: 'admin',
    tech: 'vue + typescript',
    codingUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/d/work-weixin-admin/git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['企业微信', '后台', 'work-weixin-admin'],
  },
  {
    name: '企业微信 H5',
    kind: 'h5',
    tech: 'uni-app',
    codingUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/d/work-weixin/git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['企业微信', 'H5', 'work-weixin'],
  },
  {
    name: '水卡管理后台',
    kind: 'admin',
    tech: 'vue + typescript',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/pickup-admin.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['水卡', '后台', 'pickup-admin'],
  },
  {
    name: '图片静态站',
    kind: 'static',
    tech: '静态资源站',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/mono-static.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    notes: '统一管理项目静态图片等资源，压缩图片可用 tinypng.com。',
    tags: ['静态资源', '图片', 'mono-static'],
  },
  {
    name: '云店小程序',
    kind: 'miniapp',
    tech: 'uni-app',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/cloudshop-mp.git',
    githubUrl: 'https://github.com/MiDouTech/cloudshop-mp.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    notes: '默认构建直播版；非直播版需手动构建并设置 RELEASE_ENV=NONE。',
    tags: ['云店', '小程序', 'cloudshop-mp'],
  },
  {
    name: '装修中心后台',
    kind: 'admin',
    tech: 'vue + typescript',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/decoration-center.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    notes: '使用插件包分支 feature/decoration。',
    tags: ['装修', '后台', 'decoration-center'],
  },
  {
    name: '装修 H5 预览',
    kind: 'h5',
    tech: 'uni-app',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/decorate-h5.git',
    githubUrl: 'https://github.com/MiDouTech/decorate-h5',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    tags: ['装修', 'H5', 'decorate-h5'],
  },
  {
    name: '规则中心',
    kind: 'h5',
    tech: 'uni-app',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/service-center.git',
    branches: 'test 分支自动构建测试环境；prod 分支自动构建线上环境',
    notes: 'H5 规则中心；短信访问跳转小程序。',
    tags: ['规则中心', 'H5', 'service-center'],
  },
  {
    name: '静态说明页',
    kind: 'static',
    tech: 'html + js',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/static-page.git',
    branches: 'master 分支自动构建线上环境',
    notes: '一般用作简单说明页，图片在 static 目录，页面文件在 src 目录。',
    tags: ['静态页', '说明页', 'static-page'],
  },
  {
    name: '智能营销后台页面',
    kind: 'admin',
    tech: 'JS 引入式后台页面/组件',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/fw-admin.git',
    notes: '智能营销后台页面和组件，另有关联项目 fw-bg。',
    tags: ['智能营销', '后台', 'fw-admin'],
  },
  {
    name: '智能营销背景服务页面',
    kind: 'admin',
    tech: 'JS 引入式后台页面/组件',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/fw-bg.git',
    notes: '智能营销后台相关项目，和 fw-admin 配套。',
    tags: ['智能营销', '后台', 'fw-bg'],
  },
  {
    name: '同级码上传管理后台',
    kind: 'admin',
    tech: '前后端项目',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/level_package.git',
    buildUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/ci/job?id=6423628',
    tags: ['同级码', '后台', 'level_package'],
  },
  {
    name: '成品批次管理后台',
    kind: 'admin',
    tech: '前后端项目',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/batch-admin.git',
    buildUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/ci/job?id=6601184',
    tags: ['成品批次', '后台', 'batch-admin'],
  },
  {
    name: 'PDA 总部端',
    kind: 'miniapp',
    tech: 'uni-app',
    githubUrl: 'https://github.com/MiDouTech/uniapp-pda',
    buildUrl: 'http://192.168.5.140/job/uniapp-pda/',
    tags: ['PDA', '总部端', 'uniapp-pda'],
  },
  {
    name: '扫码模板',
    kind: 'legacy',
    tech: 'SVN 模板项目',
    svnUrl: 'http://192.168.5.254/svn/ui/fw/templateMarket/trunk',
    tags: ['扫码模板', 'SVN', 'templateMarket'],
  },
  {
    name: 'uni-app 多端扫码模板',
    kind: 'miniapp',
    tech: 'uni-app',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/activity-packages.git',
    githubUrl: 'https://github.com/MiDouTech/activity-packages',
    svnUrl: 'http://192.168.5.254/svn/ui/activity/wap-uni',
    buildUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/ci/job?id=1626678',
    notes: '构建只是更新静态资源，需要到配置中心更新静态资源版本号。',
    tags: ['扫码', 'uni-app', 'activity-packages', 'wap-uni'],
  },
  {
    name: '个人中心',
    kind: 'h5',
    tech: 'vue + mint-ui',
    svnUrl: 'http://192.168.5.254/svn/ui/usercenter/trunk',
    localUrl: 'http://localhost:8080/uSERCENTER?m=13800138000',
    buildUrl: 'http://192.168.5.140/job/UserCenter_Trunk/',
    notes: '开发环境手动发布到 /usercenter/assets/project_revision_number/static/。',
    tags: ['个人中心', 'H5', 'usercenter'],
  },
  {
    name: '互动营销后台',
    kind: 'admin',
    tech: 'vue + layui + scss/css',
    svnUrl: 'http://192.168.5.254/svn/ui/activity/admin/trunk',
    buildUrl: 'http://192.168.5.140/job/Activity_Trunk_Admin/',
    notes: '开发环境手动发布到 /act/admin/assets/project_revision_number。',
    tags: ['互动营销', '后台', 'activity'],
  },
  {
    name: '互动营销前台',
    kind: 'h5',
    tech: 'vue',
    svnUrl: 'http://192.168.5.254/svn/ui/activity/wap/trunk',
    buildUrl: 'http://192.168.5.140/job/Activity_Trunk_Api/',
    notes: '前台和游戏一起构建发布。',
    tags: ['互动营销', '前台', 'H5', 'activity'],
  },
  {
    name: 'DCRM 后台',
    kind: 'admin',
    tech: 'vue + layui + scss',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/dcrm-admin.git',
    buildUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/ci/job?id=1925112',
    notes: '构建后可能需要修改配置的静态资源版本号。',
    tags: ['DCRM', '后台', 'dcrm-admin'],
  },
  {
    name: 'DCRM H5',
    kind: 'h5',
    tech: 'vue',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/dcrm-h5.git',
    buildUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/ci/job?id=1991105',
    notes: '构建后可能需要修改配置的静态资源版本号。',
    tags: ['DCRM', 'H5', 'dcrm-h5'],
  },
  {
    name: '云店品牌商后台',
    kind: 'admin',
    tech: 'vue + typescript + element-ui',
    svnUrl: 'http://192.168.5.254/svn/ui/cloudShop/member/branches',
    buildUrl: 'http://192.168.5.140/job/CloudShopApi_trunk/',
    branches: '测试分支 branches/test；线上分支 member/master',
    notes: '发布后在 ops 运维平台推送。',
    tags: ['云店', '品牌商', '后台', 'cloudShop'],
  },
  {
    name: '云店经销商后台',
    kind: 'admin',
    tech: 'vue + typescript + element-ui',
    svnUrl: 'http://192.168.5.254/svn/ui/cloudShop/dealer/trunk',
    buildUrl: 'http://192.168.5.140/job/CloudShopDealer_branches/',
    branches: '测试分支 trunk/test；线上分支 trunk/master',
    notes: '发布后在 ops 运维平台推送。',
    tags: ['云店', '经销商', '后台', 'cloudShop'],
  },
  {
    name: '云店助手端',
    kind: 'miniapp',
    tech: 'wepy',
    codingUrl: 'https://miduoyanfa.coding.net/p/pingtai/d/retail-assistant-mp/git',
    svnUrl: 'http://192.168.5.151:8090/IntelligentRetail/storeHelperMiniprogram.git',
    notes: '新版万能零售对应 Coding 项目 retail-assistant-mp。',
    tags: ['云店助手', '智慧零售', 'wepy'],
  },
  {
    name: '购物车项目',
    kind: 'h5',
    tech: 'vue + vant',
    svnUrl: 'http://192.168.5.254/svn/ui/commerce/cart/trunk',
    localUrl: 'http://localhost:8080/Cart/ShoppingCart?m=13800138000',
    tags: ['购物车', 'H5', 'commerce'],
  },
  {
    name: '积分商城项目 H5',
    kind: 'h5',
    tech: 'vue + vant',
    svnUrl: 'http://192.168.5.254/svn/ui/commerce/integral/trunk',
    notes: '手动构建发布。',
    tags: ['积分商城', 'H5', 'commerce'],
  },
  {
    name: '米多来发商城',
    kind: 'legacy',
    tech: 'vue',
    svnUrl: 'http://192.168.5.254/svn/ui/lipin/',
    buildUrl: 'http://192.168.5.38/',
    notes: '静态资源目录包括 /admin、/web、/weixin、/officialWebsite。',
    tags: ['米多来发', '商城', 'lipin'],
  },
  {
    name: '商城小程序项目',
    kind: 'miniapp',
    tech: 'wepy',
    codingUrl: 'https://e.coding.net/miduoyanfa/bigdataengine/mall-mp.git',
    buildUrl: 'https://miduoyanfa.coding.net/p/bigdataengine/ci/job?id=1376404',
    notes: '本地调试后不要提交 extConfig 固定配置；构建完成后在 BDE 总后台版本库管理填写信息。',
    tags: ['商城', '小程序', 'mall-mp'],
  },
  {
    name: '会员小程序项目后台',
    kind: 'admin',
    tech: 'vue + element-ui',
    svnUrl: 'http://192.168.5.254/svn/ui/commerce/PlusAdimin/trunk',
    buildUrl: 'http://192.168.5.140/job/Membership_Trunk_Admin/',
    notes: '开发环境手动上传到 /Membership/admin/member/project_revision_number/。',
    tags: ['会员', '后台', 'PlusAdimin'],
  },
  {
    name: '会员小程序项目小程序',
    kind: 'miniapp',
    tech: 'wepy',
    svnUrl: 'http://192.168.5.254/svn/ui/commerce/plusMemberMini/trunk',
    docUrl: 'http://192.168.5.254/svn/ui/commerce/plusMemberMini/备忘.docx',
    notes: '静态资源地址：/commerce/plusMemberMini/static/images；开发环境静态资源上传到 /Membership/MP/static/project_revision_number/images/。',
    tags: ['会员', '小程序', 'plusMemberMini'],
  },
  {
    name: '卡拉宝门店',
    kind: 'miniapp',
    tech: 'uni-app',
    svnUrl: 'http://192.168.5.254/svn/ui/karabaoStore',
    docUrl: 'http://192.168.5.254/svn/ui/karabaoStore/readme.docx',
    release: '测试环境和线上环境手动发布',
    tags: ['卡拉宝', '门店', 'uni-app'],
  },
  {
    name: '卡拉宝青苹果',
    kind: 'miniapp',
    tech: 'uni-app',
    svnUrl: 'http://192.168.5.254/svn/ui/kalabaoApple',
    docUrl: 'http://192.168.5.254/svn/ui/kalabaoApple/readme.docx',
    release: '测试环境和线上环境手动发布',
    tags: ['卡拉宝', '青苹果', 'uni-app'],
  },
  {
    name: '卡拉宝能量补给站',
    kind: 'miniapp',
    tech: 'wepy',
    svnUrl: 'http://192.168.5.254/svn/ui/kalabaoMini',
    docUrl: 'http://192.168.5.254/svn/ui/kalabaoMini/readme.docx',
    notes: '配置文件在 scancode/config；静态文件夹 /kalabaoMini/；测试和线上手动发布。',
    tags: ['卡拉宝', 'wepy', 'kalabaoMini'],
  },
  {
    name: '米互动小程序',
    kind: 'miniapp',
    tech: '小程序',
    svnUrl: 'http://192.168.5.254/svn/ui/MiDuoWan',
    notes: '包括“我讲你说”“我问你答”同一套代码；线上最新代码 ISayUSay，开发环境 utellme。',
    tags: ['米互动', '小程序', 'MiDuoWan'],
  },
  {
    name: '音频小程序',
    kind: 'miniapp',
    tech: '小程序',
    svnUrl: 'http://192.168.5.254/svn/ui/audiomini',
    docUrl: 'http://192.168.5.254/svn/ui/audiomini/备忘.docx',
    tags: ['音频', '小程序', 'audiomini'],
  },
  {
    name: '视频小程序',
    kind: 'miniapp',
    tech: '小程序',
    svnUrl: 'http://192.168.5.22:8081/2017NEWMIDUO/产品研发部/UI部/2017前端/智能营销/miniprogram/videoMini',
    tags: ['视频', '小程序', 'videoMini'],
  },
  {
    name: '石湾扫码（防伪）小程序',
    kind: 'miniapp',
    tech: '小程序',
    svnUrl: 'http://192.168.5.22:8081/2017NEWMIDUO/产品研发部/UI部/2017前端/智能营销/miniprogram/shiwan-fw',
    tags: ['石湾', '扫码', '防伪', '小程序'],
  },
  {
    name: '经销商',
    kind: 'legacy',
    tech: '前端项目',
    svnUrl: 'http://192.168.5.254/svn/ui/recovery',
    docUrl: 'http://192.168.5.254/svn/ui/recovery/备忘.docx',
    tags: ['经销商', 'recovery'],
  },
  {
    name: '社群后台',
    kind: 'admin',
    tech: '非前后端分离',
    svnUrl: 'http://192.168.5.254/svn/ui/faxian/admin',
    release: '手动发布到 /faxian/admin',
    tags: ['社群', '后台', 'faxian'],
  },
  {
    name: '社群前台',
    kind: 'h5',
    tech: '前端页面',
    svnUrl: 'http://192.168.5.22:8081/2017NEWMIDUO/产品研发部/UI部/前端/前台/社群营销/community',
    release: '手动发布到 /faxian/wap',
    tags: ['社群', '前台', 'community'],
  },
  {
    name: '大数据引擎首页',
    kind: 'site',
    tech: '站点页面',
    svnUrl: 'http://192.168.5.254/svn/khjy/home/trunk/src',
    buildUrl: 'http://192.168.5.38/job/Home_trunk/changes',
    localUrl: 'https://home.t.miduonet.com/home/default',
    notes: '站点更新归属：客户经营 - 商户后台。',
    tags: ['大数据引擎', '首页', 'home'],
  },
  {
    name: '产品域',
    kind: 'site',
    tech: '站点页面',
    svnUrl: 'http://192.168.5.254/svn/khjy/mall/trunk',
    buildUrl: 'http://192.168.5.38/job/Mall_trunk/changes',
    localUrl: 'https://bgmall.t.miduonet.com/ProductLibrary/Index.aspx',
    notes: '站点更新归属：客户经营 - 微商城。',
    tags: ['产品域', '微商城', 'mall'],
  },
  {
    name: '客户',
    kind: 'site',
    tech: '站点页面',
    svnUrl: 'http://192.168.5.254/svn/khjy/bg/trunk',
    localUrl: 'https://bg.t.miduonet.com/Usermanage/MemberSummarize.aspx',
    notes: '站点更新归属：客户经营 - 商户后台。',
    tags: ['客户', '商户后台', 'bg'],
  },
  {
    name: '标识管理',
    kind: 'site',
    tech: '站点页面',
    svnUrl: 'http://192.168.5.254/svn/bsfn/FwSystem/trunk',
    buildUrl: 'http://192.168.5.140/job/FwSystem_trunk/',
    localUrl: 'http://fwewm.t.miduonet.com/BasicSetup/YunMaManager.aspx',
    notes: '站点更新归属：标识赋能 - 防伪码管理。',
    tags: ['标识', '防伪码', 'FwSystem'],
  },
  {
    name: '品牌推广',
    kind: 'site',
    tech: '站点页面',
    svnUrl: 'http://192.168.5.254/svn/khjy/platform/trunk',
    buildUrl: 'http://192.168.5.38/job/pptg_trunk/',
    localUrl: 'https://pptg.t.miduonet.com/Article/ArticleTest/WGWHomePage.aspx',
    notes: '站点更新归属：客户经营 - 总后台。',
    tags: ['品牌推广', '总后台', 'pptg'],
  },
];

export const FRONT_END_PROJECT_KIND_LABEL: Record<FrontEndProjectKind, string> = {
  miniapp: '小程序',
  admin: '后台',
  h5: 'H5',
  static: '静态站',
  legacy: '旧项目',
  site: '站点',
};

