#!/usr/bin/env python3
"""Sync acceptance rule snapshots into official skill packages.

Repository `doc/` files are the SSOT. The snapshots under each skill are
generated fallback copies for marketplace users who download a skill outside
this repository and therefore do not have `doc/`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

SOURCES = [
    {
        "sourceId": "acceptance.rule.enterprise",
        "path": "doc/rule.acceptance.map-enterprise.md",
        "target": "rule.acceptance.map-enterprise.md",
    },
    {
        "sourceId": "acceptance.rule.ssot",
        "path": "doc/rule.acceptance.ssot.md",
        "target": "rule.acceptance.ssot.md",
    },
    {
        "sourceId": "acceptance.guide.daily-sop",
        "path": "doc/guide.acceptance.daily-sop.md",
        "target": "guide.acceptance.daily-sop.md",
    },
    {
        "sourceId": "acceptance.guide.report-evidence",
        "path": "doc/guide.acceptance.report-evidence.md",
        "target": "guide.acceptance.report-evidence.md",
    },
    {
        "sourceId": "acceptance.design.knowledge-governance",
        "path": "doc/design.acceptance.knowledge-governance.md",
        "target": "design.acceptance.knowledge-governance.md",
    },
]

SKILLS = [
    "acceptance-test-design",
    "acceptance-scenario-orchestrator",
    "create-visual-test-to-kb",
]


def git_commit() -> str:
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
        ).strip()
        source_paths = [item["path"] for item in SOURCES]
        dirty = subprocess.check_output(
            ["git", "status", "--porcelain", "--", *source_paths], cwd=ROOT, text=True
        ).strip()
        return commit + ("+worktree" if dirty else "")
    except Exception:
        return "unknown"


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def snapshot_body(source_id: str, source_path: str, source_commit: str, content_hash: str, content: str) -> str:
    header = (
        "<!--\n"
        "Generated acceptance rule snapshot. Do not edit this file directly.\n"
        f"sourceId: {source_id}\n"
        f"sourcePath: {source_path}\n"
        f"sourceCommit: {source_commit}\n"
        f"contentHash: sha256:{content_hash}\n"
        "Update with: python3 scripts/sync-acceptance-rule-snapshots.py\n"
        "-->\n\n"
    )
    return header + content.rstrip() + "\n"


def parse_snapshot(actual: str) -> tuple[str | None, str]:
    match = re.match(r"\A<!--\n(?P<header>.*?)\n-->\n\n(?P<body>.*)\Z", actual, re.S)
    if not match:
        return None, actual
    header = match.group("header")
    hash_match = re.search(r"^contentHash: (sha256:[0-9a-f]{64})$", header, re.M)
    return (hash_match.group(1) if hash_match else None), match.group("body")


def build_payload() -> tuple[str, list[dict[str, str]]]:
    source_commit = git_commit()
    docs: list[dict[str, str]] = []
    for item in SOURCES:
        path = ROOT / item["path"]
        if not path.is_file():
            raise SystemExit(f"missing source: {item['path']}")
        content = path.read_text(encoding="utf-8")
        content_hash = sha256_text(content)
        docs.append({
            **item,
            "sourceCommit": source_commit,
            "contentHash": content_hash,
            "body": snapshot_body(item["sourceId"], item["path"], source_commit, content_hash, content),
        })
    return source_commit, docs


def sync(check: bool) -> int:
    source_commit, docs = build_payload()
    generated_at = datetime.now(timezone.utc).isoformat()
    failures: list[str] = []
    for skill in SKILLS:
        rules_dir = ROOT / ".claude" / "skills" / skill / "references" / "rules"
        if check and not rules_dir.parent.is_dir():
            failures.append(f"missing skill references dir: {skill}")
            continue
        expected_manifest = {
            "kind": "acceptance-rule-snapshots",
            "sourceCommit": source_commit,
            "generatedAt": generated_at,
            "sources": [
                {
                    "sourceId": d["sourceId"],
                    "sourcePath": d["path"],
                    "snapshotPath": f"references/rules/{d['target']}",
                    "contentHash": "sha256:" + d["contentHash"],
                }
                for d in docs
            ],
        }
        manifest_path = rules_dir / "manifest.json"
        if not check:
            rules_dir.mkdir(parents=True, exist_ok=True)
        for d in docs:
            out = rules_dir / d["target"]
            if check:
                if not out.is_file():
                    failures.append(f"missing snapshot: {out.relative_to(ROOT)}")
                    continue
                actual = out.read_text(encoding="utf-8")
                actual_hash, actual_content = parse_snapshot(actual)
                expected_content = (ROOT / d["path"]).read_text(encoding="utf-8").rstrip() + "\n"
                if actual_hash != "sha256:" + d["contentHash"] or actual_content != expected_content:
                    failures.append(f"stale snapshot: {out.relative_to(ROOT)}")
            else:
                out.write_text(d["body"], encoding="utf-8")
        if check:
            if not manifest_path.is_file():
                failures.append(f"missing manifest: {manifest_path.relative_to(ROOT)}")
            else:
                try:
                    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                except Exception as exc:
                    failures.append(f"invalid manifest: {manifest_path.relative_to(ROOT)} {exc}")
                    continue
                actual_sources = [
                    {k: s.get(k) for k in ("sourceId", "sourcePath", "snapshotPath", "contentHash")}
                    for s in manifest.get("sources", [])
                ]
                expected_sources = [
                    {k: s.get(k) for k in ("sourceId", "sourcePath", "snapshotPath", "contentHash")}
                    for s in expected_manifest["sources"]
                ]
                if actual_sources != expected_sources:
                    failures.append(f"stale manifest sources: {manifest_path.relative_to(ROOT)}")
        else:
            manifest_path.write_text(json.dumps(expected_manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    print("acceptance rule snapshots are up to date" if check else "acceptance rule snapshots synced")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated snapshots are stale")
    args = parser.parse_args()
    raise SystemExit(sync(args.check))


if __name__ == "__main__":
    main()
